### ISSUE TITLE
Excessive _callbackTimer output on terminal in debug mode in 0.2.1

### ISSUE THREAD

**Issue by azizLIGHT** [kozec/sc-controller#15]
I'm trying to debug the [crash issue](https://github.com/kozec/sc-controller/issues/14), but since upgrading to 0.2.1 the terminal output is spammed with "_callbackTimer" too many times. Important information gets scrolled out of view because "_callbackTimer" is repeating many times per second. Is this intentional?

Here is a sample of terminal output: 

```
aziz@LIGHT:~$ scc-daemon null debug
D Mapper        Creating virtual devices
D Mapper        Gamepad:  <scc.uinput.Gamepad object at 0x7fc3ae2ac090>
D Mapper        Keyboard: <scc.uinput.Keyboard object at 0x7fc3ac812d90>
D Mapper        Mouse:    <scc.uinput.Mouse object at 0x7fc3ac812e90>
W SCCDaemon     Failed to load profile. Starting with no mappings.
W SCCDaemon     Reason: [Errno 2] No such file or directory: 'null'
D SCCDaemon     Starting SCCDaemon...
D SCCDaemon     Created control socket /home/aziz/.config/scc/daemon.socket
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
I SCCDaemon     Loaded profile '/home/aziz/.config/scc/profiles/Rocket League.sccprofile'
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
D SCCDaemon     Controller turned ON
	I SCCDaemon     Loaded profile 'Desktop'
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
	_callbackTimer
_callbackTimer
I SCCDaemon     Loaded profile 'Rocket League'
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
^CD SCCDaemon     Break
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
^C_callbackTimer
_callbackTimer
Traceback (most recent call last):
  File "/usr/bin/scc-daemon", line 28, in <module>
    _main()
  File "/usr/bin/scc-daemon", line 26, in _main
    daemon.debug()
  File "/usr/lib/python2.7/dist-packages/scc/sccdaemon.py", line 294, in debug
    self.remove_socket()
  File "/usr/lib/python2.7/dist-packages/scc/sccdaemon.py", line 280, in remove_socket
    self.sserver.shutdown()
  File "/usr/lib/python2.7/SocketServer.py", line 251, in shutdown
    self.__is_shut_down.wait()
  File "/usr/lib/python2.7/threading.py", line 620, in wait
    self.__cond.wait(timeout)
  File "/usr/lib/python2.7/threading.py", line 339, in wait
    waiter.acquire()
KeyboardInterrupt
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
_callbackTimer
^C_callbackTimer
Exception KeyboardInterrupt in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
aziz@LIGHT:~$ 

```

**Comment by azizLIGHT** [comment]
This was not happening on 0.2.0 FYI

**Comment by kozec** [comment]
Ah, yeah. I love forgetting about debug stuff :(

**Comment by kozec** [comment]
... and included in [latest release](https://github.com/kozec/sc-controller/releases/tag/v0.2.2)
