### ISSUE TITLE
Mouse Wheel not working

### ISSUE THREAD

**Issue by Kierek** [kozec/sc-controller#162]
For a few days Mouse Wheel seems to stopped working for me when using the default Desktop profile.

> I SCCDaemon     Loaded profile 'Desktop'
D OSD DaemonCtrlr   Daemon reported profile change: /home/kierek/.config/scc/profiles/Desktop.sccprofile
D OSD Config        Configuration saved
D OSD osd.daemon    Updated recent profile list
E Mapper        Error while processing controller event
E Mapper        Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/scc/mapper.py", line 333, in input
    self.profile.pads[LEFT].whole(self, state.lpad_x, state.lpad_y, LEFT)
  File "/usr/lib/python2.7/site-packages/scc/modifiers.py", line 423, in whole
    self.action.change(mapper, dx * self.speed[0], dy * self.speed[1])
  File "/usr/lib/python2.7/site-packages/scc/actions.py", line 1789, in _change
    WholeHapticAction.change(self, x, y)
TypeError: change() takes exactly 4 arguments (3 given)

>E Mapper        Error while processing controller event
E Mapper        Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/scc/mapper.py", line 338, in input
    self.profile.pads[LEFT].whole(self, 0, 0, LEFT)
  File "/usr/lib/python2.7/site-packages/scc/modifiers.py", line 428, in whole
    self._roll(mapper)
  File "/usr/lib/python2.7/site-packages/scc/modifiers.py", line 366, in _roll
    self.action.change(mapper, dx * self.speed[0], dy * self.speed[1])
  File "/usr/lib/python2.7/site-packages/scc/actions.py", line 1789, in _change
    WholeHapticAction.change(self, x, y)
TypeError: change() takes exactly 4 arguments (3 given)

**Comment by kozec** [comment]
Fixed. Sorry about that.
