### ISSUE TITLE
Unable to open settings for touchpads

### ISSUE THREAD

**Issue by Kierek** [kozec/sc-controller#165]
Sometimes I'm unable to open settings for touchpads when they are set to mouse wheel or trackball(RStick works fine).

> [kierek@kierekDesktop ~]$ sc-controller 
pidfile /home/kierek/.config/scc/daemon.pid does not exist. Daemon not running?
W App           Daemon reported unknown profile: '/dev/null'; Overriding.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/scc/gui/controller_widget.py", line 149, in on_click
    self.app.show_editor(self.id)
  File "/usr/lib/python2.7/site-packages/scc/gui/app.py", line 214, in show_editor
    ae = self.choose_editor(action, "")
  File "/usr/lib/python2.7/site-packages/scc/gui/binding_editor.py", line 141, in choose_editor
    e = ActionEditor(self.app, self.on_action_chosen)
  File "/usr/lib/python2.7/site-packages/scc/gui/action_editor.py", line 100, in __init__
    self.load_components()
  File "/usr/lib/python2.7/site-packages/scc/gui/action_editor.py", line 151, in load_components
    self.load_component(c)
  File "/usr/lib/python2.7/site-packages/scc/gui/action_editor.py", line 162, in load_component
    mod = importlib.import_module("scc.gui.ae.%s" % (class_name,))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/scc/gui/ae/osk_action.py", line 12, in <module>
    from scc.constants import Keys, LEFT, RIGHT
ImportError: cannot import name Keys

**Comment by kozec** [comment]
Looks like I'm going another release today :(
