### ISSUE TITLE
Error importing individual vdf files

### ISSUE THREAD

**Issue by neuromancer** [kozec/sc-controller#198]
Hi,

I'm trying to import a particular vdf file that contains the steam controller configuration. For instance, this [one](https://www.steamcontrollerdb.com/config/the-witcher/gibbletgravys-bindings/5486). Is it a planned feature?

Thanks!

**Comment by kozec** [comment]
It is already supported and SCC even registers itself as handler for their vdffz files. You can also  drag&drop vdf or vdffz file to application window.

Is there any problem with this specific one? I can't test is right now.

**Comment by neuromancer** [comment]
> It is already supported and SCC even registers itself as handler for their vdffz files. You can also drag&drop vdf or vdffz file to application window.

Oh neat!, Drag & Drop works but in Linux there is no easy way to register a program to handle files (in all the desktops). 

> Is there any problem with this specific one? I can't test is right now.

I just tried it, this is the error:

```
Unknown key: 'DASH'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/scc/gui/importexport/import_vdf.py", line 357, in import_vdf
    self._profile.load(filename)
  File "/usr/lib/python2.7/site-packages/scc/foreign/vdf.py", line 577, in load
    self.load_data(data)
  File "/usr/lib/python2.7/site-packages/scc/foreign/vdf.py", line 593, in load_data
    VDFProfile._load_preset(data, self, p)
  File "/usr/lib/python2.7/site-packages/scc/foreign/vdf.py", line 534, in _load_preset
    profile.parse_input_binding(data, group_id, binding)
  File "/usr/lib/python2.7/site-packages/scc/foreign/vdf.py", line 453, in parse_input_binding
    action = self.parse_group(group, Profile.LEFT)
  File "/usr/lib/python2.7/site-packages/scc/foreign/vdf.py", line 315, in parse_group
    keys.append(self.parse_button(inputs[k]))
  File "/usr/lib/python2.7/site-packages/scc/foreign/vdf.py", line 234, in parse_button
    return self.parse_action(bdef, button)
  File "/usr/lib/python2.7/site-packages/scc/foreign/vdf.py", line 105, in parse_action
    b = VDFProfile.convert_key_name(params[0])
  File "/usr/lib/python2.7/site-packages/scc/foreign/vdf.py", line 211, in convert_key_name
    raise ParseError("Unknown key: '%s'" % (name,))
ParseError: Unknown key: 'DASH'

Profile filename: /home/g/Downloads/gibbletgravys Bindings.vdf

Profile dump:
"controller_mappings"
{
	"version"		"2"
	"title"		"gibbletgravy's Bindings"
	"description"		"Optimized for Controller based of Ingwersaft"
	"creator"		"76561198057360985"
	"group"
	{
		"id"		"0"
		"mode"		"four_buttons"
		"bindings"
		{
			"button_A"		"key_press X, Fast Style"
			"button_B"		"key_press C, Group Style"
			"button_X"		"key_press Z, Strong Style"
			"button_Y"		"key_press TAB, No Combat"
		}
		"settings"
		{
			"hold_repeat_inverval"		"99"
			"button_size"		"17992"
			"button_dist"		"19992"
		}
	}
	"group"
	{
		"id"		"1"
		"mode"		"dpad"
		"bindings"
		{
			"dpad_north"		"key_press DASH, Weapon 1"
			"dpad_south"		"key_press SPACE, Weapon 3"
			"dpad_east"		"key_press 8, Weapon 2"
			"dpad_west"		"key_press 6, Weapon 4"
		}
		"settings"
		{
			"overlap"		"0"
			"hold_repeat_inverval"		"99"
			"deadzone"		"5000"
			"edge_binding_radius"		"24996"
			"analog_emulation_period"		"29"
		}
	}
	"group"
	{
		"id"		"2"
		"mode"		"absolute_mouse"
		"bindings"
		{
			"click"		"key_press LEFT_ALT, Show Objects"
		}
		"settings"
		{
			"sensitivity"		"141"
			"rotation"		"15"
			"doubetap_max_duration"		"320"
		}
	}
	"group"
	{
		"id"		"3"
		"mode"		"dpad"
		"bindings"
		{
			"dpad_north"		"key_press W, Move Forward"
			"dpad_south"		"key_press S, Move Back"
			"dpad_east"		"key_press D, Move Right"
			"dpad_west"		"key_press A, Move Left"
			"click"		"key_press F, Rotate 180"
		}
		"settings"
		{
			"requires_click"		"0"
			"hold_repeat_inverval"		"99"
			"edge_binding_radius"		"24995"
			"haptic_intensity"		"0"
			"analog_emulation_period"		"29"
		}
	}
	"group"
	{
		"id"		"4"
		"mode"		"trigger"
		"bindings"
		{
			"edge"		"mouse_button RIGHT"
		}
		"settings"
		{
			"hold_repeat_inverval"		"99"
		}
	}
	"group"
	{
		"id"		"5"
		"mode"		"trigger"
		"bindings"
		{
			"click"		"mouse_button LEFT"
		}
		"settings"
		{
			"hold_repeat_inverval"		"99"
		}
	}
	"group"
	{
		"id"		"6"
		"mode"		"four_buttons"
		"bindings"
		{
			"button_A"		"key_press SPACE, Pause"
			"button_B"		"key_press 8, Quick Slot 3"
			"button_X"		"key_press 6, Quick Slot 1"
			"button_Y"		"key_press DASH, Next Sign"
		}
		"settings"
		{
			"button_size"		"17984"
			"button_dist"		"19968"
		}
	}
	"group"
	{
		"id"		"7"
		"mode"		"four_buttons"
		"bindings"
		{
			"button_A"		"key_press L, Alchemy"
			"button_B"		"key_press M, Map"
			"button_X"		"key_press H, Hero"
			"button_Y"		"key_press F9, Quick Load"
		}
		"settings"
		{
			"button_size"		"17984"
			"button_dist"		"19982"
		}
	}
	"preset"
	{
		"id"		"0"
		"name"		""
		"group_source_bindings"
		{
			"0"		"button_diamond active"
			"1"		"left_trackpad inactive"
			"6"		"left_trackpad active"
			"7"		"left_trackpad inactive modeshift"
			"2"		"right_trackpad active"
			"3"		"joystick active"
			"4"		"left_trigger active"
			"5"		"right_trigger active"
		}
		"switch_bindings"
		{
			"bindings"
			{
				"button_back_left"		"key_press LEFT_SHIFT, Journal"
				"button_escape"		"key_press ESCAPE, Menu"
				"left_bumper"		"key_press Q, Steel Sword"
				"right_bumper"		"key_press E, Silver Sword"
				"button_back_right"		"key_press I, Inventory"
				"right_trigger"		"mode_shift left_trackpad 7"
				"button_menu"		"key_press F5, Quick Save"
			}
		}
		"settings"
		{
		}
	}
}
```

**Comment by kozec** [comment]
Ok, so as quick fix, open it in editor and replace both occurrences of `key_press DASH` with `key_press MINUS`. I'll add it to list of weirdly named keys later :)

> Oh neat!, Drag & Drop works but in Linux there is no easy way to register a program to handle files (in all the desktops).

Actually, registering [mime types](https://github.com/kozec/sc-controller/blob/master/scc-mime-types.xml#L4) and adding that mime type to [desktop file](https://github.com/kozec/sc-controller/blob/master/sc-controller.desktop#L10) should work with any DE. Just out of curiosity, what are you using?

**Comment by neuromancer** [comment]
It works, but the imported profile is not shown in the list inmediately. Reloading sc-controller fixs that issue.

Btw, I'm using [Budgie](https://solus-project.com/budgie/) (mostly GNOME based). To open vdf files, Files only offers me Mousepad and Emacs. 
In any case, don't worry about this, I don't expect to have support for such "rare" desktop and Drag & Drop is fine for me. Integration with a website like steamcontrollerdb (or others) could be really useful.

**Comment by kozec** [comment]
> Integration with a website like steamcontrollerdb (or others) could be really useful.

That's what that desktop & mime magic is supposed to do. On my XFCE, I can click on "Download Config" and it goes directly to import dialog. I have Budgie VM at home, so I'll check what went wrong, but if they are doing registration in some different way, there may be nothing I can do about it :(

**Comment by kozec** [comment]
So, I found what problem with vdff files was, Solus doesn't recognize json files by default and chain of mime types was `text/plain -> application/json -> application/x-steamcontrollerdb-profile`. I believe removing that middle part should fix it.
