### ISSUE TITLE
Broken touchpad with Ring + Feedback + Circular

### ISSUE THREAD

**Issue by DFOXpro** [kozec/sc-controller#212]
## Setup

Put this text in custom Editor in any of the touchpads and confirm

    ring(0.75,
      feedback(LEFT, 512, 3.0,   sens(1, 1,     circular(axis(Axes.ABS_X)))),
      feedback(LEFT, 256, 6.0,   sens(0.2, 0.2,     circular(axis(Axes.ABS_X))))
    )

## What do you want

After confirm the touchpad must work like a steering wheel with smooth control in the outer ring and fast control in the inner ring

## What really happen

The driver simply return no data from the touchpad and the sc-controller (gui) throw this error when click Custom Editor in touchpad:

    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/scc/gui/ring_editor.py", line 114, in on_btCustomActionEditor_clicked
        e.set_input(self.id, self._make_action(), mode = self.mode)
      File "/usr/lib/python2.7/dist-packages/scc/gui/action_editor.py", line 951, in set_input
        self.set_action(action)
      File "/usr/lib/python2.7/dist-packages/scc/gui/action_editor.py", line 768, in set_action
        entAction.set_text(action.to_string())
      File "/usr/lib/python2.7/dist-packages/scc/actions.py", line 1915, in to_string
        return MultichildAction.to_string(self, multiline, pad, "%s, " % (self.radius,))
      File "/usr/lib/python2.7/dist-packages/scc/actions.py", line 1197, in to_string
        ])) + ")"
      File "/usr/lib/python2.7/dist-packages/scc/modifiers.py", line 1147, in to_string
        return self._mod_to_string(self.strip_defaults(), multiline, pad)
      File "/usr/lib/python2.7/dist-packages/scc/modifiers.py", line 70, in _mod_to_string
        childstr = self.action.to_string(False, pad)
      File "/usr/lib/python2.7/dist-packages/scc/modifiers.py", line 1090, in to_string
        while speeds[-1] == 1.0:
    IndexError: list index out of range

The scc-daemon debug throws:

    W Actions       Action FeedbackModifier can't handle whole stick event

**Comment by DFOXpro** [comment]
I test even more without feedback  and with just one sensor modifier:

    ring(0.75,
      circular(axis(Axes.ABS_X)),
      sens(0.2, 0.2,     circular(axis(Axes.ABS_X)))
    )

This solve the sc-controller exception (looks like sens(1.0,1.0, action) crash the gui), but the driver returns on touchpad touched the same error even without feedback()

**Comment by kozec** [comment]
Error should be fixed, but I have yet to test if emulation works as expected, as I don't have controller here right now.

**Comment by kozec** [comment]
Ok, emulation works as well.
