### ISSUE TITLE
Cannot set Action to an "Execute Command"

### ISSUE THREAD

**Issue by xPMo** [kozec/sc-controller#332]
Output of `sc-controller --debug`

    D App           daemon status: unknown
    D DaemonCtrl    Connected to daemon, version 0.4.0.2
    D DaemonCtrl    Daemon is ready.
    D App           daemon status: alive
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/scc/gui/ae/special_action.py", line 129, in on_cbActionType_changed
        self.on_enCommand_changed()
      File "/usr/lib/python2.7/site-packages/scc/gui/ae/special_action.py", line 173, in on_enCommand_changed
        self.editor.set_action(ShellCommandAction(enCommand.get_text().decode("utf-8")))
      File "/usr/lib/python2.7/site-packages/scc/gui/action_editor.py", line 802, in set_action
        entAction.set_text(action.to_string())
      File "/usr/lib/python2.7/site-packages/scc/special_actions.py", line 83, in to_string
        return (" " * pad) + "%s('%s')" % (self.COMMAND, self.parameters[0].encode('string_escape'))
    TypeError: escape_encode() argument 1 must be string, not unicode

The TypeError repeats on every character entered.  My locale is `en_DK.UTF-8`, so nothing out of the ordinary.

changing `'string_escape'` to `'unicode_escape'` seems to fix it, but I don't know enough about Python 2's Unicode handling to know if this is best practice.

**Comment by kozec** [comment]
Weird thing is that it is getting unicode there. What are you entering as command?

**Comment by xPMo** [comment]
Anything. It errors when the input box is empty, or when it's something like `urxvt` or `i3-msg focus up`. I'm not putting in anything outside ASCII.
