### ISSUE TITLE
Can't Edit Pressed Action for stick

### ISSUE THREAD

**Issue by abrasive** [kozec/sc-controller#336]
Using with a Steam controller, attempting to "Edit Pressed Action" on the stick yields
```
Traceback (most recent call last):
  File "/home/jhl/.local/lib64/python2.7/site-packages/scc/gui/app.py", line 461, in on_mnuEditPress_activate
    self.show_editor(getattr(SCButtons, self.context_menu_for))
  File "/home/jhl/.local/lib64/python2.7/site-packages/scc/lib/enum.py", line 422, in __getattr__
    raise AttributeError(name)
AttributeError: STICK
```

It works fine on both pads, just not the stick.

**Comment by abrasive** [comment]
Ah... but I can left click on the left half of the button to get to the STICKPRESS action. Just the context menu doesn't work.

**Comment by kozec** [comment]
Yeah, that's what I get for renaming constants after 2 years of using it :(
