### ISSUE TITLE
SyntaxError: Non-ASCII character '\xe2' in file /sc-controller/scc/lib/xinput.py

### ISSUE THREAD

**Issue by Leiaz** [kozec/sc-controller#338]
Using the master branch, the daemon cannot start : 
```
Traceback (most recent call last):
  File "/home/leiaz/opensource/sc-controller/scripts/scc-daemon", line 2, in <module>
    from scc.sccdaemon import SCCDaemon
  File "/home/leiaz/opensource/sc-controller/scc/sccdaemon.py", line 9, in <module>
    from scc.lib import xinput
  File "/home/leiaz/opensource/sc-controller/scc/lib/xinput.py", line 28
SyntaxError: Non-ASCII character '\xe2' in file /home/leiaz/opensource/sc-controller/scc/lib/xinput.py on line 28, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

```
It looks like `# -*- coding: utf-8 -*-` was accidentally removed in 18a70ce5b725053d5adbd29a9fce8dfa88d7fc7c.

Great app, much more usable than Steam's GUI.

**Comment by kozec** [comment]
It's not that I didn't fixed that right away, I just forgot to commit that change :)
