### ISSUE TITLE
SCC-Daemon failing to start

### ISSUE THREAD

**Issue by LinuxJoeUser** [kozec/sc-controller#368]
I'm stumped.  I'm on a clean install of Xubuntu 18.04.  Here's the `scc-daemon debug` output:
```
gw@Marianne:~$ scc-daemon debug
Traceback (most recent call last):
  File "/usr/local/bin/scc-daemon", line 36, in <module>
    main()
  File "/usr/local/bin/scc-daemon", line 15, in main
    daemon = SCCDaemon(get_pid_file(), get_daemon_socket())
  File "/usr/local/lib/python2.7/dist-packages/scc/sccdaemon.py", line 48, in __init__
    self.dev_monitor = create_device_monitor(self)
  File "/usr/local/lib/python2.7/dist-packages/scc/device_monitor.py", line 279, in create_device_monitor
    m = Eudev().monitor(subclass=DeviceMonitor)
  File "/usr/local/lib/python2.7/dist-packages/scc/lib/eudevmonitor.py", line 30, in __init__
    self._lib = ctypes.CDLL(self.LIB_NAME + ".so")
  File "/usr/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libudev.so: cannot open shared object file: No such file or directory
```
And  here are the dependencies I've installed:

**python 2.7, GTK 3.22 or newer and PyGObject:**
```
python2.7:amd64 <none> 2.7.15~rc1-1
python-dev:amd64 2.7.15~rc1-1
libgtk-3-common:all <none> 3.22.30-1ubuntu1
python-gobject/bionic,bionic,now 3.26.1-2 all
```
**python-gi-cairo and gir1.2-rsvg-2.0 on debian based distros**
```
python-gi-cairo:amd64 <none> 3.26.1-2
gir1.2-rsvg-2.0:amd64 <none> 2.40.20-2
```
**setuptools (don't know which is appropriate)**
```
python-setuptools:all <none> 39.0.1-2
pypy-setuptools:all <none> 39.0.1-2
```
**python-pylibacl recommended:**  `python-pylibacl:amd64 <none> 0.5.3-1build2`

**python-evdev strongly recommended**  `python-evdev:amd64 <none> 0.7.0+dfsg-2`

And because of the mention of `libudev.so` missing, I installed `libudev1:i386` then I thought I should stop and just report it as an issue.

**Comment by kozec** [comment]
Interesting, I somehow assumed that libudev will be available everywhere. I'll check it with VM, but before that, what gives you `file /usr/lib/libudev.*` ?

**Comment by kozec** [comment]
Here. Hopefully, new Ubuntu had same issues as old Ubuntu.

**Comment by LinuxJoeUser** [comment]
Yeah, `file /usr/lib/libudev` doesn't exist.  A quick search turned up a good list of possible candidates though, as you can see below.  Also, thanks for the patch, it worked *perfectly.*

```
gw@Marianne:/$ apt search libudev
Sorting... Done
Full Text Search... Done
libeeze-dev/bionic 1.8.6-2.5build1 amd64
  EEZE headers and static libraries

libeeze1/bionic 1.8.6-2.5build1 amd64
  Library for manipulating devices through udev

libgudev-1.0-0/bionic,now 1:232-2 amd64 [installed]
  GObject-based wrapper library for libudev

libgudev1.0-cil/bionic,bionic 0.1-4build1 all
  GObject-based wrapper library for libudev -- CLI bindings

libgudev1.0-cil-dev/bionic,bionic 0.1-4build1 all
  GObject-based wrapper library for libudev -- CLI development files

libgudev3.0-cil/bionic,bionic 3.0.0-1build1 all
  GObject-based wrapper library for libudev -- CLI bindings

libgudev3.0-cil-dev/bionic,bionic 3.0.0-1build1 all
  GObject-based wrapper library for libudev -- CLI development files

libudev-dev/bionic 237-3ubuntu10 amd64
  libudev development files

libudev1/bionic,now 237-3ubuntu10 amd64 [installed]
  libudev shared library

monodoc-gudev-manual/bionic,bionic 3.0.0-1build1 all
  compiled XML documentation for gudev-sharp

python-pyudev/bionic,bionic 0.21.0-1 all
  Python bindings for libudev

python3-pyudev/bionic,bionic 0.21.0-1 all
  Python3 bindings for libudev

scanbd/bionic 1.5.1-2 amd64
  Scanner button daemon

```

**Comment by LinuxJoeUser** [comment]
whoops, didn't mean to close it.  I'll leave that to you to decide when it's fixed the way you want it. :)

**Comment by kozec** [comment]
That fix should be OK, it uses library search function that I should've used in first place :)
