### ISSUE TITLE
Sc-Controller not loading daemon

### ISSUE THREAD

**Issue by Blad3forc3** [kozec/sc-controller#370]
Getting this debug error when running sc-controller

```
D SCCDaemon     Starting SCCDaemon...
D SCCDaemon     Initializing drivers...
Traceback (most recent call last):
  File "/usr/bin/scc-daemon", line 36, in <module>
    main()
  File "/usr/bin/scc-daemon", line 32, in main
    daemon.debug()
  File "/usr/lib/python2.7/dist-packages/scc/sccdaemon.py", line 1077, in debug
    self.run()
  File "/usr/lib/python2.7/dist-packages/scc/sccdaemon.py", line 623, in run
    self.init_drivers()
  File "/usr/lib/python2.7/dist-packages/scc/sccdaemon.py", line 85, in init_drivers
    mod = getattr(__import__('scc.drivers.%s' % (modname,)).drivers, modname)
  File "/usr/lib/python2.7/dist-packages/scc/drivers/ds4drv.py", line 8, in <module>
    from scc.drivers.hiddrv import BUTTON_COUNT, ButtonData, AxisType, AxisData
  File "/usr/lib/python2.7/dist-packages/scc/drivers/hiddrv.py", line 14, in <module>
    from scc.drivers.evdevdrv import FIRST_BUTTON, TRIGGERS, parse_axis
  File "/usr/lib/python2.7/dist-packages/scc/drivers/evdevdrv.py", line 19, in <module>
    import evdev
  File "/usr/local/lib/python2.7/dist-packages/evdev/__init__.py", line 9, in <module>
    from evdev.uinput import UInput, UInputError
  File "/usr/local/lib/python2.7/dist-packages/evdev/uinput.py", line 35
    def from_device(cls, *devices, filtered_types=(ecodes.EV_SYN, ecodes.EV_FF), **kwargs):
                                                ^
SyntaxError: invalid syntax
```

**Comment by kozec** [comment]
I see multiple things broken at once...

What distro are you running? Can you check to which package "/usr/local/lib/python2.7/dist-packages/evdev/uinput.py" file belongs?

**Comment by kozec** [comment]
Actually, it's probably just one thing, python-evdev package. But I can't imagine why would that happen nor why would not distro maintainer caught that immediately.

**Comment by Blad3forc3** [comment]
I'm using kde neon. how do i check that file belongs?

**Comment by kozec** [comment]
Well, that depends... :D

But Kde Neon is Ubuntu-based, IIRC, so hopefully `dpkg-query -S /usr/local/lib/python2.7/dist-packages/evdev/uinput.py`

**Comment by Blad3forc3** [comment]
ok here's the result

dpkg-query: no path found matching pattern /usr/local/lib/python2.7/dist-packages/evdev/uinput.py

**Comment by kozec** [comment]
Ok, so it appears that you somehow have python-evdev installed without package manager knowing about that. Maybe you've installed it manually, or some script did that for you. And it's on [version that's broken](https://github.com/gvalkov/python-evdev/issues/83). So either upgrade it, downgrade it, or get rid of it and install one from package :)

**Comment by Blad3forc3** [comment]
ive removed the evdev package and its still doing the same thing, same error

**Comment by kozec** [comment]
And is that file still there?
