### ISSUE TITLE
AttributeError: 'Cycle' object has no attribute 'repeat'

### ISSUE THREAD

**Issue by CreamyCookie** [kozec/sc-controller#395]
When I want to configure the left bumper (configured as "Cycle between 2 weapons") in the attached profile I get this exception:

```python
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/scc/gui/controller_widget.py", line 64, in on_click
    self.app.show_editor(self.id)
  File "/usr/lib/python2.7/dist-packages/scc/gui/app.py", line 374, in show_editor
    ae = self.choose_editor(action, "", id)
  File "/usr/lib/python2.7/dist-packages/scc/gui/binding_editor.py", line 158, in choose_editor
    elif isinstance(action, Macro) and not (is_button_togle(action) or is_button_repeat(action)):
  File "/usr/lib/python2.7/dist-packages/scc/gui/ae/buttons.py", line 214, in is_button_repeat
    if isinstance(action, Macro) and action.repeat:
AttributeError: 'Cycle' object has no attribute 'repeat'
```

profile / configuration:

```json
{
    "buttons": {
        "A": {
            "action": "button(Keys.KEY_ENTER)", 
            "name": "Confirm"
        }, 
        "B": {
            "action": "button(Keys.KEY_N)", 
            "modes": {
                "LGRIP": {
                    "action": "button(Keys.KEY_F3)", 
                    "name": "Data [Pipboy]"
                }
            }, 
            "name": "Back"
        }, 
        "BACK": {
            "action": "button(Keys.KEY_TAB)", 
            "name": "Pipboy"
        }, 
        "LB": {
            "action": "cycle(button(Keys.KEY_1), button(Keys.KEY_3))", 
            "name": "Cycle between 2 weapons"
        }, 
        "LGRIP": {
            "action": "button(Keys.KEY_F)", 
            "name": "Activate"
        }, 
        "RB": {
            "action": "button(Keys.BTN_LEFT)", 
            "name": "Attack immediately"
        }, 
        "RGRIP": {
            "action": "button(Keys.KEY_K)", 
            "name": "Reload / Put weapon away"
        }, 
        "RPAD": {
            "action": "button(Keys.KEY_SPACE)", 
            "name": "Jump"
        }, 
        "START": {
            "action": "button(Keys.KEY_ESC)", 
            "name": "Menu"
        }, 
        "STICK": {
            "action": "button(Keys.KEY_LEFTCTRL)", 
            "name": "Crouch"
        }, 
        "X": {
            "action": "button(Keys.KEY_Q)", 
            "modes": {
                "LGRIP": {
                    "action": "button(Keys.KEY_F1)", 
                    "name": "Stats [Pipboy]"
                }
            }, 
            "name": "Mod weapon"
        }, 
        "Y": {
            "action": "button(Keys.KEY_K)", 
            "modes": {
                "LGRIP": {
                    "action": "button(Keys.KEY_F2)", 
                    "name": "Items [Pipboy]"
                }
            }, 
            "name": "Repair weapon"
        }
    }, 
    "gyro": {
        "modes": {
            "C": {
                "action": "mouse(ROLL)"
            }
        }, 
        "name": "Look", 
        "sensitivity": [3.5, 3.5, 3.5]
    }, 
    "menus": {
        "Fallout New Vegas": [{
            "name": "careful", 
            "separator": true
        }, {
            "action": "button(Keys.KEY_F5)", 
            "id": "item2", 
            "name": "Quick Save"
        }, {
            "name": ".", 
            "separator": true
        }, {
            "action": "button(Keys.KEY_F9)", 
            "id": "item4", 
            "name": "Quick Load"
        }, {
            "name": "rest", 
            "separator": true
        }, {
            "action": "button(Keys.KEY_F); button(Keys.KEY_F); button(Keys.KEY_F); button(Keys.KEY_F); button(Keys.KEY_F); button(Keys.KEY_F); button(Keys.KEY_F); button(Keys.KEY_F); button(Keys.KEY_F); button(Keys.KEY_F); button(Keys.KEY_F); button(Keys.KEY_F); button(Keys.KEY_F); button(Keys.KEY_F); button(Keys.KEY_F); button(Keys.KEY_F); button(Keys.KEY_F); button(Keys.KEY_F); button(Keys.KEY_F); button(Keys.KEY_F); button(Keys.KEY_F); button(Keys.KEY_F); button(Keys.KEY_F); button(Keys.KEY_F); button(Keys.KEY_F); button(Keys.KEY_F); button(Keys.KEY_T); button(Keys.KEY_H)", 
            "id": "item6", 
            "name": "Casino"
        }, {
            "action": "button(Keys.KEY_F4)", 
            "id": "item7", 
            "name": "Command Prompt"
        }, {
            "action": "button(Keys.KEY_M)", 
            "id": "item8", 
            "name": "Special vision"
        }, {
            "action": "button(Keys.KEY_L)", 
            "id": "item9", 
            "name": "Wait"
        }, {
            "action": "button(Keys.KEY_D)", 
            "id": "item10", 
            "name": "Take all"
        }, {
            "action": "button(Keys.KEY_B)", 
            "id": "item11", 
            "name": "Pull"
        }, {
            "action": "button(Keys.KEY_W)", 
            "id": "item12", 
            "name": "VATS"
        }]
    }, 
    "pad_left": {
        "action": "menu('Fallout New Vegas')", 
        "osd": true
    }, 
    "pad_right": {
        "action": "mouse()", 
        "ball": true, 
        "feedback": ["RIGHT", 256], 
        "modes": {
            "C": {
                "X": {
                    "action": "mouse(Rels.REL_HWHEEL, 1.0)"
                }, 
                "Y": {
                    "action": "mouse(Rels.REL_WHEEL, 1.0)"
                }, 
                "ball": true, 
                "feedback": ["RIGHT", 4096, 16], 
                "name": "Zoom / Scroll"
            }
        }
    }, 
    "stick": {
        "dpad": [{
            "action": "button(Keys.KEY_UP)"
        }, {
            "action": "button(Keys.KEY_DOWN)"
        }, {
            "action": "button(Keys.KEY_LEFT)"
        }, {
            "action": "button(Keys.KEY_RIGHT)"
        }], 
        "name": "Move"
    }, 
    "trigger_left": {
        "action": "button(Keys.KEY_LEFTSHIFT)", 
        "levels": [50, 255], 
        "name": "Run"
    }, 
    "trigger_right": {
        "actions": [{
            "action": "button(Keys.BTN_RIGHT)", 
            "levels": [50, 255]
        }, {
            "action": "button(Keys.BTN_LEFT)", 
            "levels": [254, 255]
        }], 
        "name": "Attack / Shield"
    }, 
    "version": 1.2
}
```

**Version:** 0.4.3

**Comment by kozec** [comment]
Thanks for reporting, fixed :)
