### ISSUE TITLE
AssertionError: udevlibrary not found

### ISSUE THREAD

**Issue by rummik** [kozec/sc-controller#401]
Output from `scc-daemon debug`:
```
Traceback (most recent call last):
  File "/nix/store/k974g5d9m2i1ri2yj6ax3yqsl22hrr45-sc-controller-0.4.3/bin/..scc-daemon-wrapped-wrapped", line 37, in <module>
    main()
  File "/nix/store/k974g5d9m2i1ri2yj6ax3yqsl22hrr45-sc-controller-0.4.3/bin/..scc-daemon-wrapped-wrapped", line 16, in main
    daemon = SCCDaemon(get_pid_file(), get_daemon_socket())
  File "/nix/store/k974g5d9m2i1ri2yj6ax3yqsl22hrr45-sc-controller-0.4.3/lib/python2.7/site-packages/scc/sccdaemon.py", line 48, in __init__
    self.dev_monitor = create_device_monitor(self)
  File "/nix/store/k974g5d9m2i1ri2yj6ax3yqsl22hrr45-sc-controller-0.4.3/lib/python2.7/site-packages/scc/device_monitor.py", line 279, in create_device_monitor
    m = Eudev().monitor(subclass=DeviceMonitor)
  File "/nix/store/k974g5d9m2i1ri2yj6ax3yqsl22hrr45-sc-controller-0.4.3/lib/python2.7/site-packages/scc/lib/eudevmonitor.py", line 31, in __init__
    assert find_library(self.LIB_NAME), self.LIB_NAME + "library not found"
AssertionError: udevlibrary not found
```

Some searching suggests this is caused by a bug in `find_library`, and some weird file locations.  There was a fix submitted for pyudev over at pyudev/pyudev#117 that can probably be adapted

As a note, I'm using this under NixOS, so file locations are a little different than on most other distros

**Comment by rnhmjoj** [comment]
I'm another NixOS user and contributor: I tried sc-controller with https://github.com/kozec/sc-controller/commit/25f1d63aa5893a7a66eec242bd048543714434cf but it doesn't seem to work, unlike the patch rummik proposed.
@kozec could you try this [patch](https://raw.githubusercontent.com/rnhmjoj/nixpkgs/5914624410d37f3f96560214609c4a0c73310d1d/pkgs/misc/drivers/sc-controller/fix-udev.patch) and tell me if it works on other distros as well?

**Comment by kozec** [comment]
It appears to work with everything I thrown at it, so let's check what completely random thing will it broke :)

**Comment by rnhmjoj** [comment]
Great!

**Comment by rummik** [comment]
0b00ece is working on my end as well

**Comment by kozec** [comment]
Glad to hear that :)
