### ISSUE TITLE
sc-controller not working anymore: Failed to create uinput device. Error code: -1

### ISSUE THREAD

**Issue by WebFreak001** [kozec/sc-controller#415]
After some time I wanted to use sc-controller again but it has stopped working (I did updates of kernel and sc-controller)

scc-daemon debug output log:
```
D SCCDaemon     Starting SCCDaemon...
D SCCDaemon     Initializing drivers...
W SCCDaemon     Skipping disabled driver 'fake'
D USB           Registered USB driver for 054c:09cc
D USB           Registered USB driver for 28de:1102
D USB           Registered USB driver for 28de:1142
D Mapper        Creating virtual devices
E SCCDaemon     Failed to create uinput device. Error code: -1
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/scc/sccdaemon.py", line 442, in init_mapper
    self.scheduler, poller=self.poller)
  File "/usr/lib/python2.7/site-packages/scc/mapper.py", line 39, in __init__
    self.keyboard = self.create_keyboard(keyboard) if keyboard else Dummy()
  File "/usr/lib/python2.7/site-packages/scc/mapper.py", line 98, in create_keyboard
    return Keyboard(name=name)
  File "/usr/lib/python2.7/site-packages/scc/uinput.py", line 538, in __init__
    keyboard=True)
  File "/usr/lib/python2.7/site-packages/scc/uinput.py", line 268, in __init__
    raise CannotCreateUInputException("Failed to create uinput device. Error code: %s" % (self._fd,))
CannotCreateUInputException: Failed to create uinput device. Error code: -1
D Mapper        Creating virtual devices
D Mapper        Keyboard: <scc.uinput.Dummy object at 0x7f576940f110>
D Mapper        Mouse:    <scc.uinput.Dummy object at 0x7f576940f150>
D Mapper        Gamepad:  <scc.uinput.Dummy object at 0x7f576940f190>
D SCCDaemon     Created control socket /home/webfreak/.config/scc/daemon.socket
D SCCDaemon     Connected to XServer :0
D USB           USB device added: 28de:1142
D OSD DaemonCtrl    Connected to daemon, version 0.4.4
D OSD DaemonCtrl    Daemon reported error 'Failed to create uinput device. Error code: -1'
```

however if I now press the big steam button on my controller for the first time it prints this:
```
D SCDongle      Not requesting serial number for SC sc1
D SCDongle      Got wireless SC with serial sc1
D SCCDaemon     Assigned default_mapper to <SCWireless sc1>
D SCCDaemon     Controller added: <SCWireless sc1>
D OSD DaemonCtrl    Daemon reported profile change for sc1: /home/webfreak/.config/scc/profiles/Desktop.sccprofile
W SCCDaemon     Cannot show OSD; there is no scc-osd-daemon registered
```

It seems like it's detecting the controller but it can't control my PC anymore.

```
4.18.5-arch1-1-ARCH
```

**Comment by WebFreak001** [comment]
Fixed in 4.18.6-zen1-1-zen
