### ISSUE TITLE
AppImage doesn't launch

### ISSUE THREAD

**Issue by simbalion** [kozec/sc-controller#429]
```
g_module_open() failed for /tmp/.mount_sc-coni4iAW1/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so: /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /tmp/.mount_sc-coni4iAW1/usr/lib/libpng16.so.16)
/tmp/.mount_sc-coni4iAW1/AppRun: line 44: 27650 Segmentation fault      gdk-pixbuf-query-loaders > "$GDK_PIXBUF_MODULE_FILE"

** (process:27652): WARNING **: Failed to load shared library 'libgdk-3.so.0' referenced by the typelib: /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /tmp/.mount_sc-coni4iAW1/usr/lib/libpng16.so.16)
Traceback (most recent call last):
  File "/tmp/.mount_sc-coni4iAW1/usr/bin/sc-controller", line 20, in <module>
    from gi.repository import Gtk, GObject
  File "/tmp/.mount_sc-coni4iAW1/usr/lib/python2.7/site-packages/gi/importer.py", line 145, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/tmp/.mount_sc-coni4iAW1/usr/lib/python2.7/site-packages/gi/importer.py", line 146, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/tmp/.mount_sc-coni4iAW1/usr/lib/python2.7/site-packages/gi/overrides/__init__.py", line 125, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/tmp/.mount_sc-coni4iAW1/usr/lib/python2.7/site-packages/gi/overrides/Gdk.py", line 81, in <module>
    Color = override(Color)
  File "/tmp/.mount_sc-coni4iAW1/usr/lib/python2.7/site-packages/gi/overrides/__init__.py", line 202, in override
    assert g_type != TYPE_NONE
AssertionError
```

**Comment by kozec** [comment]
What distro are you running it on and what's version of libz package?

**Comment by simbalion** [comment]
Debian 9
There is no libz package

**Comment by kozec** [comment]
I've added libz to appimage for v0.4.6.
