### ISSUE TITLE
Unable to import .VDF file - unknown buttons

### ISSUE THREAD

**Issue by Kierek** [kozec/sc-controller#453]
When trying to import *.vdf file I get multiple parsing errors.

```
Unknown button: 'left_trigger_threshold'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/scc/gui/importexport/import_vdf.py", line 357, in import_vdf
    self._profile.load(filename)
  File "/usr/lib/python2.7/site-packages/scc/foreign/vdf.py", line 578, in load
    self.load_data(data)
  File "/usr/lib/python2.7/site-packages/scc/foreign/vdf.py", line 594, in load_data
    VDFProfile._load_preset(data, self, p)
  File "/usr/lib/python2.7/site-packages/scc/foreign/vdf.py", line 535, in _load_preset
    profile.parse_input_binding(data, group_id, binding)
  File "/usr/lib/python2.7/site-packages/scc/foreign/vdf.py", line 447, in parse_input_binding
    self.parse_switches(group)
  File "/usr/lib/python2.7/site-packages/scc/foreign/vdf.py", line 440, in parse_switches
    raise ParseError("Unknown button: '%s'" % (button,))
ParseError: Unknown button: 'left_trigger_threshold'
```

After deleting all occurrences of left_trigger_threshold, there is a problem with unknown key single_button, then unknown key equals. I haven't tested further yet.

[metroid prime 1 (trilogy) v1.2_0.txt](https://github.com/kozec/sc-controller/files/2865837/metroid.prime.1.trilogy.v1.2_0.txt)
(renamed as .txt since github doesn't support .vdf)

**Comment by kozec** [comment]
Yeah, that import code is probably few months behind what's Steam generating currently :(

I'll try checking on what got changed over weekend.
