### ISSUE TITLE
   how to install python-evdev

### ISSUE THREAD

**Issue by faheemq** [kozec/sc-controller#476]
m@faheem-HP-Laptop-15-db0xxx:~$ scc-daemon debug
D SCCDaemon     Starting SCCDaemon...
D SCCDaemon     Initializing drivers...
W SCCDaemon     Skipping disabled driver 'ds4drv'
W SCCDaemon     Skipping disabled driver 'fake'
W SCCDaemon     Skipping disabled driver 'remotepad'
W evdev         Failed to enable Evdev driver: 'python-evdev' package is missing.
D USB           Registered USB driver for 28de:1102
D USB           Registered USB driver for 28de:1142
D Mapper        Creating virtual devices
E SCCDaemon     Failed to create uinput device. Error code: -1
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/scc/sccdaemon.py", line 448, in init_mapper
    self.scheduler, poller=self.poller)
  File "/usr/lib/python2.7/dist-packages/scc/mapper.py", line 39, in __init__
    self.keyboard = self.create_keyboard(keyboard) if keyboard else Dummy()
  File "/usr/lib/python2.7/dist-packages/scc/mapper.py", line 98, in create_keyboard
    return Keyboard(name=name)
  File "/usr/lib/python2.7/dist-packages/scc/uinput.py", line 538, in __init__
    keyboard=True)
  File "/usr/lib/python2.7/dist-packages/scc/uinput.py", line 268, in __init__
    raise CannotCreateUInputException("Failed to create uinput device. Error code: %s" % (self._fd,))
CannotCreateUInputException: Failed to create uinput device. Error code: -1
D Mapper        Creating virtual devices
D Mapper        Keyboard: <scc.uinput.Dummy object at 0x7f0decb0f2d0>
D Mapper        Mouse:    <scc.uinput.Dummy object at 0x7f0decb0f310>
D Mapper        Gamepad:  <scc.uinput.Dummy object at 0x7f0decb0f350>
D SCCDaemon     Created control socket /home/faheem/.config/scc/daemon.socket
D SCCDaemon     Connected to XServer :0.0
D OSD DaemonCtrl    Connected to daemon, version 0.4.6
D OSD DaemonCtrl    Daemon reported error 'Failed to create uinput device. Error code: -1'
^CTraceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/scc/x11/scc-osd-daemon.py", line 314, in <module>
D SCCDaemon     Break
    d.run()
  File "/usr/lib/python2.7/dist-packages/scc/x11/scc-osd-daemon.py", line 304, in run

**Comment by kozec** [comment]
[Depends on distro.](https://python-evdev.readthedocs.io/en/latest/install.html)

**Comment by faheemq** [comment]
i have linux mint 
which ubuntu one?
