### ISSUE TITLE
Non-ASCII gamepad name 

### ISSUE THREAD

**Issue by JostBrand** [kozec/sc-controller#492]
Trying to add an Xiaomi Gamepad which has a chinese name.
Crashes the dialog to save the config.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/scc/gui/creg/dialog.py", line 401, in on_btNext_clicked
    self.save_registration()
  File "/usr/lib/python2.7/site-packages/scc/gui/creg/dialog.py", line 331, in save_registration
    filename = self._evdevice.name.strip().replace("/","")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/scc/gui/creg/dialog.py", line 401, in on_btNext_clicked
    self.save_registration()
  File "/usr/lib/python2.7/site-packages/scc/gui/creg/dialog.py", line 331, in save_registration
    filename = self._evdevice.name.strip().replace("/","")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
```

**Comment by kozec** [comment]
Can you post that name so I can test potential fix?

**Comment by JostBrand** [comment]
小米蓝牙手柄
