### ISSUE TITLE
AttributeError when attempting to register a custom controller

### ISSUE THREAD

**Issue by SynthRose** [kozec/sc-controller#511]
I am running Debian Bullseye and SC-Controller v0.4.7.

When attempting to register the PowerA Wireless GameCube Controller (which displays as "Lic Pro Controller"), I encounter the following error after clicking "Next" on the screen where you set the controller layout:
```
Traceback (most recent call last):
  File "/tmp/.mount_SC_Conlbx3ru/usr/lib/python2.7/site-packages/scc/gui/creg/dialog.py", line 395, in on_btNext_clicked
    self.prepare_registration(dev)
  File "/tmp/.mount_SC_Conlbx3ru/usr/lib/python2.7/site-packages/scc/gui/creg/dialog.py", line 460, in prepare_registration
    retry_with_evdev(None, 0)
  File "/tmp/.mount_SC_Conlbx3ru/usr/lib/python2.7/site-packages/scc/gui/creg/dialog.py", line 441, in retry_with_evdev
    for s in tester.__signals: tester.disconnect(s)
AttributeError: 'NoneType' object has no attribute '_ControllerRegistration__signals'
```
The GUI then fails to continue with configuration. I'm not getting this issue with my (first-party) Switch Pro Controller, although that controller only works with evdev input, which must be changed manually (otherwise, no inputs are read at all).

I also tried this on the experimental 0.4.9.9 version, to the same result - though I'm not entirely sure if it built it correctly, as the GUI still displays the version as v0.4.7.

**Comment by kozec** [comment]
Okay, from bottom.

> I also tried this on the experimental 0.4.9.9 version, to the same result - though I'm not entirely sure if it built correctly, as the GUI still displays the version as v0.4.7.

That's OK, 0.4.9.9 has still version set to v0.4.7 internally. But there is no support for udev/hid controllers yet, so it is not going to help you anyway.

For main issue, [it should be already fixed](https://github.com/kozec/sc-controller/commit/85a6414bfb40c1bfc8b9968cfef051636e396254) and fix will be included in next release.
