### ISSUE TITLE
Python Decode Error

### ISSUE THREAD

**Issue by mozzribo** [kozec/sc-controller#549]
Hello!

Everything worked fine, and then seemingly out of the blue:

`Traceback (most recent call last):
  File "/usr/bin/sc-controller", line 28, in <module>
    App(glades, images).run(sys.argv)
  File "/usr/lib/python2.7/site-packages/scc/gui/app.py", line 55, in __init__
    self.convert_old_profiles()
  File "/usr/lib/python2.7/site-packages/scc/gui/app.py", line 1631, in convert_old_profiles
    if name.endswith("~"):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)`

On Manjaro Linux.

Any idea on how to fix this? Or maybe what went wrong on my side?

**Comment by mozzribo** [comment]
Something that might be of use:

I tried to save a profile with a non-ASCII character "é". The software didn't react (nothing happened when I clicked on "Create"). I might have pressed create several times. I changed "é" to "e" and then I was able to create the profile. I'm not sure if this has anything to do with it, since SC-Controller ran several times afterwards.

I have since removed the software (via AUR), searched for any file that might cause the error, removed all temporary files from the system, rebooted, TimeShifted, nothing helped, I still get the same error.
