### ISSUE TITLE
Steam config

### ISSUE THREAD

**Issue by cptMikky** [kozec/sc-controller#583]

**Comment by cptMikky** [comment]
update:
maybe the issue is somewhere else. This is what I get when clicking the "import from Steam" button
```
Traceback (most recent call last):
  File "/nix/store/5rb2lrhqmymng4h511byvkkh2s33blaj-sc-controller-0.4.7/lib/python2.7/site-packages/scc/gui/importexport/dialog.py", line 172, in on_btImportVdf_clicked
    self.next_page(grVdfImport)
  File "/nix/store/5rb2lrhqmymng4h511byvkkh2s33blaj-sc-controller-0.4.7/lib/python2.7/site-packages/scc/gui/importexport/dialog.py", line 116, in next_page
    self._page_selected(page)
  File "/nix/store/5rb2lrhqmymng4h511byvkkh2s33blaj-sc-controller-0.4.7/lib/python2.7/site-packages/scc/gui/importexport/dialog.py", line 125, in _page_selected
    getattr(self, hname)()
  File "/nix/store/5rb2lrhqmymng4h511byvkkh2s33blaj-sc-controller-0.4.7/lib/python2.7/site-packages/scc/gui/importexport/import_vdf.py", line 44, in on_grVdfImport_activated
    self.on_tvVdfProfiles_cursor_changed()
  File "/nix/store/5rb2lrhqmymng4h511byvkkh2s33blaj-sc-controller-0.4.7/lib/python2.7/site-packages/scc/gui/importexport/import_vdf.py", line 248, in on_tvVdfProfiles_cursor_changed
    filename = model.get_value(iter, 3)
TypeError: Argument 1 does not allow None as a value
```

**Comment by DDzwiedziu** [comment]
I can confirm.
