### ISSUE TITLE
Settings menu doesn't open

### ISSUE THREAD

**Issue by Kojlax** [kozec/sc-controller#597]
As of latest commit, opening settings from the drop down menu results in the following traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/scc/gui/app.py", line 478, in on_mnuGlobalSettings_activate
    gs = GlobalSettings(self)
  File "/usr/lib/python2.7/site-packages/scc/gui/global_settings.py", line 72, in __init__
    self.load_settings()
  File "/usr/lib/python2.7/site-packages/scc/gui/global_settings.py", line 113, in load_settings
    self.load_controllers()
  File "/usr/lib/python2.7/site-packages/scc/gui/global_settings.py", line 834, in load_controllers
    drv, name = filename.split("-", 1)
ValueError: need more than 1 value to unpack
```

**Comment by Kojlax** [comment]
On a new linux install and everything works fine? so I'm going to just assume this was a dependency error. I'm just gonna close the issue unless you or anyone else can make sense of the traceback as anything other than "I messed up the dependencies"
