### ISSUE TITLE
v0.4.8 launch issue

### ISSUE THREAD

**Issue by danrobi11** [kozec/sc-controller#601]
```
$ sudo ./sc-controller-0.4.8.glibc-x86_64.AppImage
[sudo] password for danrobi: 
python2: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_sc-conqv7whh/usr/lib/libpython2.7.so.1.0)

(zenity:28541): GdkPixbuf-WARNING **: 10:53:22.081: Cannot open pixbuf loader module file '/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.

(zenity:28541): GdkPixbuf-WARNING **: 10:53:22.146: Cannot open pixbuf loader module file '/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.

(zenity:28541): Gtk-WARNING **: 10:53:22.147: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.

(zenity:28541): GdkPixbuf-WARNING **: 10:53:22.147: Cannot open pixbuf loader module file '/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/gnome/48x48/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
/tmp/.mount_sc-conqv7whh/AppRun: line 28: 28541 Aborted                 "$@"
```
>Try running the command
  gdk-pixbuf-query-loaders > /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being
```
$ gdk-pixbuf-query-loaders > /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
bash: /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache: No such file or directory
```

**Comment by krotax01** [comment]
Same here. It seems that it's looking for loadres.cache in /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache but I've it in /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache

If I symlink the whole directory, still get this error:
```
Traceback (most recent call last):
  File "/tmp/.mount_sc-conYTcjhT/usr/bin/scc", line 6, in <module>
    from scc.scripts import main
  File "/tmp/.mount_sc-conYTcjhT/usr/lib/python2.7/site-packages/scc/scripts.py", line 8, in <module>
    from scc.tools import init_logging, set_logging_level, find_binary
  File "/tmp/.mount_sc-conYTcjhT/usr/lib/python2.7/site-packages/scc/tools.py", line 15, in <module>
    import os, sys, ctypes, imp, shlex, gettext, logging
  File "/tmp/.mount_sc-conYTcjhT/usr/lib/python2.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.7: cannot open shared object file: No such file or directory

(zenity:264859): Gtk-WARNING **: 12:17:53.059: Failed to set text 'Traceback (most recent call last):
  File "/tmp/.mount_sc-conYTcjhT/usr/bin/scc", line 6, in <module>
    from scc.scripts import main
  File "/tmp/.mount_sc-conYTcjhT/usr/lib/python2.7/site-packages/scc/scripts.py", line 8, in <module>
    from scc.tools import init_logging, set_logging_level, find_binary
  File "/tmp/.mount_sc-conYTcjhT/usr/lib/python2.7/site-packages/scc/tools.py", line 15, in <module>
    import os, sys, ctypes, imp, shlex, gettext, logging
  File "/tmp/.mount_sc-conYTcjhT/usr/lib/python2.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.7: cannot open shared object file: No such file or directory' from markup due to error parsing markup: Error en la línea 10, carácter 93: Element “markup” was closed, but the currently open element is “module”
```

**Comment by SwampRabbit** [comment]
Did either of you post this on the MX Linux forum?  I haven't seen this issue reported.

By chance are you running MX AHS or KDE?

FWIW, I am packaging and testing this version right now, if things go well it will be in the repo first chance I get.

**Comment by SwampRabbit** [comment]
@danrobi11 @krotax01 

Did either of you post this on the MX Linux forum?  I haven't seen this issue reported.

By chance are you running MX AHS or KDE?

FWIW, I am packaging and testing this version right now, if things go well it will be in the repo first chance I get.

**Comment by danrobi11** [comment]
@SwampRabbit I did not reported to MX forum. Didnt thought it was a distro specific issue. 
WM: Spectrwm
> I am packaging and testing this version right now, if things go well it will be in the repo first chance I get

Thanks!

**Comment by SwampRabbit** [comment]
> @SwampRabbit I did not reported to MX forum. Didnt thought it was a distro specific issue.
> WM: Spectrwm
> 
> > I am packaging and testing this version right now, if things go well it will be in the repo first chance I get
> 
> Thanks!

It may not be, it may be the appimage in general and/or the appimage on MX Linux.

But I've packaged several versions for MX Linux now, so you shouldn't have to use the appimage.

sc-controller built fine, installs and launches in a MX-19 AHS VM just fine, will test on a physical system with a Steam controller soon.

**Comment by krotax01** [comment]
> @danrobi11 @krotax01
> 
> Did either of you post this on the MX Linux forum? I haven't seen this issue reported.
> 
> By chance are you running MX AHS or KDE?
> 
> FWIW, I am packaging and testing this version right now, if things go well it will be in the repo first chance I get.

Didn't post in MX Linux forum. Running Kubuntu 20.10.

**Comment by ryanayoung** [comment]
I just attempted to launch for the first time and I'm having the same problem. running Pop! OS 20.10
