### ISSUE TITLE
Does not work on POP!OS 20.10

### ISSUE THREAD

**Issue by Somamint** [kozec/sc-controller#628]
The appimage won't open on POP!OS 20.10.

Anything i can offer to help, let me know :)

**Comment by kozec** [comment]
Try running it in terminal and check whether it outputs anything.

**Comment by Somamint** [comment]
sh sc-controller-0.4.8.glibc-x86_64.AppImage
sc-controller-0.4.8.glibc-x86_64.AppImage: 1: Syntax error: "(" unexpected

**Comment by Somamint** [comment]
if i start it in lutris just to get more information i got this 

sc-controller-0.4.8.glibc-x86_64.AppImage
Initial process has started with pid 16968
Game is considered started.
Traceback (most recent call last):
  File "/tmp/.mount_sc-conFXVeTg/usr/bin/scc", line 6, in <module>
    from scc.scripts import main
  File "/tmp/.mount_sc-conFXVeTg/usr/lib/python2.7/site-packages/scc/scripts.py", line 8, in <module>
    from scc.tools import init_logging, set_logging_level, find_binary
  File "/tmp/.mount_sc-conFXVeTg/usr/lib/python2.7/site-packages/scc/tools.py", line 15, in <module>
    import os, sys, ctypes, imp, shlex, gettext, logging
  File "/tmp/.mount_sc-conFXVeTg/usr/lib/python2.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.7: cannot open shared object file: No such file or directory

(zenity:16977): GdkPixbuf-WARNING **: 09:34:01.138: Cannot open pixbuf loader module file '/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache': Datei oder Verzeichnis nicht gefunden

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.

(zenity:16977): Gtk-WARNING **: 09:34:01.185: Failed to set text 'Traceback (most recent call last):
  File "/tmp/.mount_sc-conFXVeTg/usr/bin/scc", line 6, in <module>
    from scc.scripts import main
  File "/tmp/.mount_sc-conFXVeTg/usr/lib/python2.7/site-packages/scc/scripts.py", line 8, in <module>
    from scc.tools import init_logging, set_logging_level, find_binary
  File "/tmp/.mount_sc-conFXVeTg/usr/lib/python2.7/site-packages/scc/tools.py", line 15, in <module>
    import os, sys, ctypes, imp, shlex, gettext, logging
  File "/tmp/.mount_sc-conFXVeTg/usr/lib/python2.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.7: cannot open shared object file: No such file or directory' from markup due to error parsing markup: Fehler in Zeile 10, Zeichen 93: Element “markup” was closed, but the currently open element is “module”

(zenity:16977): GdkPixbuf-WARNING **: 09:34:01.204: Cannot open pixbuf loader module file '/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache': Datei oder Verzeichnis nicht gefunden

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.

(zenity:16977): Gtk-WARNING **: 09:34:01.204: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.

(zenity:16977): GdkPixbuf-WARNING **: 09:34:01.204: Cannot open pixbuf loader module file '/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache': Datei oder Verzeichnis nicht gefunden

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Pop/48x48/status/image-missing.png: Format der Bilddatei unbekannt (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Pop/48x48/status/image-missing.png: Format der Bilddatei unbekannt (gdk-pixbuf-error-quark, 3)

**Comment by konsumer** [comment]
I get similar on Pop!OS 20.10 with `sc-controller-0.4.8.glibc-x86_64.AppImage`:


```
Traceback (most recent call last):
  File "/tmp/.mount_sc-conu49Sv5/usr/bin/scc", line 6, in <module>
    from scc.scripts import main
  File "/tmp/.mount_sc-conu49Sv5/usr/lib/python2.7/site-packages/scc/scripts.py", line 8, in <module>
    from scc.tools import init_logging, set_logging_level, find_binary
  File "/tmp/.mount_sc-conu49Sv5/usr/lib/python2.7/site-packages/scc/tools.py", line 15, in <module>
    import os, sys, ctypes, imp, shlex, gettext, logging
  File "/tmp/.mount_sc-conu49Sv5/usr/lib/python2.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.7: cannot open shared object file: No such file or directory

(zenity:71699): Gtk-WARNING **: 17:29:23.792: Failed to set text 'Traceback (most recent call last):
  File "/tmp/.mount_sc-conu49Sv5/usr/bin/scc", line 6, in <module>
    from scc.scripts import main
  File "/tmp/.mount_sc-conu49Sv5/usr/lib/python2.7/site-packages/scc/scripts.py", line 8, in <module>
    from scc.tools import init_logging, set_logging_level, find_binary
  File "/tmp/.mount_sc-conu49Sv5/usr/lib/python2.7/site-packages/scc/tools.py", line 15, in <module>
    import os, sys, ctypes, imp, shlex, gettext, logging
  File "/tmp/.mount_sc-conu49Sv5/usr/lib/python2.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.7: cannot open shared object file: No such file or directory' from markup due to error parsing markup: Error on line 10 char 93: Element “markup” was closed, but the currently open element is “module”

(zenity:71699): Gtk-WARNING **: 17:29:23.808: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Pop/48x48/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Pop/48x48/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
/tmp/.mount_sc-conu49Sv5/AppRun: line 28: 71699 Aborted                 (core dumped) "$@"
```

**Comment by xenon205** [comment]
I'm on a 21.04 POP! OS and i also have the same problem with running appimage

`./sc-controller.AppImage 
Traceback (most recent call last):
  File "/tmp/.mount_sc-conjq6UH6/usr/bin/scc", line 6, in <module>
    from scc.scripts import main
  File "/tmp/.mount_sc-conjq6UH6/usr/lib/python2.7/site-packages/scc/scripts.py", line 8, in <module>
    from scc.tools import init_logging, set_logging_level, find_binary
  File "/tmp/.mount_sc-conjq6UH6/usr/lib/python2.7/site-packages/scc/tools.py", line 15, in <module>
    import os, sys, ctypes, imp, shlex, gettext, logging
  File "/tmp/.mount_sc-conjq6UH6/usr/lib/python2.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.7: cannot open shared object file: No such file or directory

(zenity:126388): GdkPixbuf-WARNING **: 13:28:36.911: Cannot open pixbuf loader module file '/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.

(zenity:126388): Gtk-WARNING **: 13:28:36.990: Failed to set text 'Traceback (most recent call last):
  File "/tmp/.mount_sc-conjq6UH6/usr/bin/scc", line 6, in <module>
    from scc.scripts import main
  File "/tmp/.mount_sc-conjq6UH6/usr/lib/python2.7/site-packages/scc/scripts.py", line 8, in <module>
    from scc.tools import init_logging, set_logging_level, find_binary
  File "/tmp/.mount_sc-conjq6UH6/usr/lib/python2.7/site-packages/scc/tools.py", line 15, in <module>
    import os, sys, ctypes, imp, shlex, gettext, logging
  File "/tmp/.mount_sc-conjq6UH6/usr/lib/python2.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.7: cannot open shared object file: No such file or directory' from markup due to error parsing markup: Error on line 10 char 93: Element “markup” was closed, but the currently open element is “module”

(zenity:126388): GdkPixbuf-WARNING **: 13:28:37.046: Cannot open pixbuf loader module file '/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.

(zenity:126388): Gtk-WARNING **: 13:28:37.046: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.

(zenity:126388): GdkPixbuf-WARNING **: 13:28:37.047: Cannot open pixbuf loader module file '/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Pop/48x48/status/image-missing.png: Unrecognised image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Pop/48x48/status/image-missing.png: Unrecognised image file format (gdk-pixbuf-error-quark, 3)
/tmp/.mount_sc-conjq6UH6/AppRun: line 28: 126388 Aborted                 (core dumped) "$@"
`

**Comment by xenon205** [comment]
by chance i found this "sudo snap install sc-controller" and it works.

**Comment by peregrin-tux** [comment]
I am on a 22.04 POP!_OS and have the same problem running appimage.

`<pre>Traceback (most recent call last):
  File &quot;/tmp/.mount_sc-conjAzDYL/usr/bin/scc&quot;, line 6, in &lt;module&gt;
    from scc.scripts import main
  File &quot;/tmp/.mount_sc-conjAzDYL/usr/lib/python2.7/site-packages/scc/scripts.py&quot;, line 8, in &lt;module&gt;
    from scc.tools import init_logging, set_logging_level, find_binary
  File &quot;/tmp/.mount_sc-conjAzDYL/usr/lib/python2.7/site-packages/scc/tools.py&quot;, line 15, in &lt;module&gt;
    import os, sys, ctypes, imp, shlex, gettext, logging
  File &quot;/tmp/.mount_sc-conjAzDYL/usr/lib/python2.7/ctypes/__init__.py&quot;, line 7, in &lt;module&gt;
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.7: cannot open shared object file: No such file or directory

(zenity:251942): GdkPixbuf-<font color="#B58900"><b>WARNING</b></font> **: <font color="#268BD2">14:15:22.798</font>: Cannot open pixbuf loader module file &apos;/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache&apos;: No existe el archivo o el directorio

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders &gt; /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.

(zenity:251942): Gtk-<font color="#B58900"><b>WARNING</b></font> **: <font color="#268BD2">14:15:22.875</font>: Failed to set text &apos;Traceback (most recent call last):
  File &quot;/tmp/.mount_sc-conjAzDYL/usr/bin/scc&quot;, line 6, in &lt;module&gt;
    from scc.scripts import main
  File &quot;/tmp/.mount_sc-conjAzDYL/usr/lib/python2.7/site-packages/scc/scripts.py&quot;, line 8, in &lt;module&gt;
    from scc.tools import init_logging, set_logging_level, find_binary
  File &quot;/tmp/.mount_sc-conjAzDYL/usr/lib/python2.7/site-packages/scc/tools.py&quot;, line 15, in &lt;module&gt;
    import os, sys, ctypes, imp, shlex, gettext, logging
  File &quot;/tmp/.mount_sc-conjAzDYL/usr/lib/python2.7/ctypes/__init__.py&quot;, line 7, in &lt;module&gt;
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.7: cannot open shared object file: No such file or directory&apos; from markup due to error parsing markup: Error en la línea 10, carácter 93: Se cerró el elemento «markup», pero el elemento que está abierto actualmente es «module»

(zenity:251942): GdkPixbuf-<font color="#B58900"><b>WARNING</b></font> **: <font color="#268BD2">14:15:22.972</font>: Cannot open pixbuf loader module file &apos;/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache&apos;: No existe el archivo o el directorio

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders &gt; /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.

(zenity:251942): Gtk-<font color="#B58900"><b>WARNING</b></font> **: <font color="#268BD2">14:15:22.972</font>: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.

(zenity:251942): GdkPixbuf-<font color="#B58900"><b>WARNING</b></font> **: <font color="#268BD2">14:15:22.973</font>: Cannot open pixbuf loader module file &apos;/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache&apos;: No existe el archivo o el directorio

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders &gt; /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Adwaita/48x48/status/image-missing.png: No se ha reconocido el formato de imagen del archivo (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Adwaita/48x48/status/image-missing.png: No se ha reconocido el formato de imagen del archivo (gdk-pixbuf-error-quark, 3)
/tmp/.mount_sc-conjAzDYL/AppRun: línea 28: 251942 Abortado         (`core&apos; generado) \" $@ \"

`
