### ISSUE TITLE
snap version 4.8 POP!OS can't find any device

### ISSUE THREAD

**Issue by xenon205** [kozec/sc-controller#637]
Appimage version didn't work on POP so i tried to install one from snap and it did work but there are a lot of errors

**Running app :**
"ERROR: ld.so: object 'libesets_pac.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libesets_pac.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libesets_pac.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libesets_pac.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libesets_pac.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libesets_pac.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libesets_pac.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libesets_pac.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libesets_pac.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libesets_pac.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libesets_pac.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libesets_pac.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libesets_pac.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libesets_pac.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libesets_pac.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libesets_pac.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libesets_pac.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libesets_pac.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libesets_pac.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libesets_pac.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libesets_pac.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libesets_pac.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libesets_pac.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libesets_pac.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libesets_pac.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
Gtk-Message: 17:59:38.488: Failed to load module "appmenu-gtk-module"

(sc-controller:91251): dbind-WARNING **: 17:59:38.490: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-TrERQPp0tE: No such file or directory
ERROR: ld.so: object 'libesets_pac.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
W App           Failed to read release notes
E App           g-io-error-quark: Operation not supported (15)
Traceback (most recent call last):
  File "/snap/sc-controller/77/lib/python2.7/site-packages/scc/gui/app.py", line 1516, in http_ready
    stream = f.read_finish(task)
Error: g-io-error-quark: Operation not supported (15)
W App           (above error is not fatal and can be ignored)"

**looking for device **
List of devices is empty and refreshing does nothing, pressing next gives more errors
"Traceback (most recent call last):
  File "/snap/sc-controller/77/lib/python2.7/site-packages/scc/gui/creg/dialog.py", line 375, in on_btNext_clicked
    dev = evdev.InputDevice(model[iter][0])
  File "/snap/sc-controller/77/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 814, in __getitem__
    aiter = self._getiter(key)
  File "/snap/sc-controller/77/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 802, in _getiter
    aiter = self.get_iter(key)
  File "/snap/sc-controller/77/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 836, in get_iter
    path = self._coerce_path(path)
  File "/snap/sc-controller/77/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 811, in _coerce_path
    return TreePath(path)
  File "/snap/sc-controller/77/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 1175, in __new__
    path = ":".join(str(val) for val in path)
TypeError: 'NoneType' object is not iterable"

**Comment by kozec** [comment]
I'm not one who is making snap and flatpack packages. It would be better to ask packager directly.
As far as I know, they are sandboxed, so not having access to any devices is not that surprising.
