### ISSUE TITLE
App is stuck in the KDE notification area, with no way to roll back settings or make customizations. 

### ISSUE THREAD

**Issue by setibeings** [kozec/sc-controller#650]
I am on `sc-controller-git v0.4.8.6.r5.76ebfefa-1` installed from the AUR, and I am using KDE Plasma

After I messed with some settings, the app always starts minimized to the notification area, and apparently cannot be un-minimized, leaving me unable to configure anything. 

Here's what I get if I try to run the application from the command line:

```
I StatusIcon    Using backend StatusIconGTK3 (primary)

(sc-controller:2876): Gtk-CRITICAL **: 15:01:29.853: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
/usr/lib/python3.9/site-packages/scc/gui/statusicon.py:266: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3 as appindicator
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/scc/gui/statusicon.py", line 336, in _on_notify_active_gtk
    self._load_fallback()
  File "/usr/lib/python3.9/site-packages/scc/gui/statusicon.py", line 353, in _load_fallback
    self._status_fb.connect(b"clicked",        self._on_click)
TypeError: GObject.connect() argument 1 must be str, not bytes

(sc-controller:2876): Gtk-CRITICAL **: 15:01:29.858: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(sc-controller:2876): Gtk-CRITICAL **: 15:01:29.858: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(sc-controller:2876): Gtk-CRITICAL **: 15:01:29.858: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

```

The only menu items on the notification icon are "Enable emulation", "About", and "Quit"

**Comment by setibeings** [comment]
I edited `/home/$USER/.config/scc` with the following values:
```
        "minimize_on_start": false, 
        "minimize_to_status_icon": false, 
```

and now it launches normally. I'm still thinking it's a bug for the program to become permanently unusable because of a box I checked in the GUI.

**Comment by kozec** [comment]
> v0.4.8.6.r5

That's suspiciously large number, latest sc-controller version is v0.4.8.

>  File "/usr/lib/python3.9/site-packages/scc/gui/statusicon.py", line 353, in _load_fallback
>    self._status_fb.connect(b"clicked",        self._on_click)
> TypeError: GObject.connect() argument 1 must be str, not bytes

I'm afraid that you are running python3 port and hitting piece of code that was not converted. You'll have to find where is AUR taking their sources from and open issue there.

**Comment by setibeings** [comment]
Okay thanks. I'm not using it for now, but next time I try it out, I'll keep in mind that the official way to do it is to follow the readme here for installation.
