### ISSUE TITLE
Can't run on Fedora 33: python2-gobject is no longer in the repositories

### ISSUE THREAD

**Issue by Scopt97** [kozec/sc-controller#675]
Basically the title. This dependency is no longer in the repositories because Python 2 has been long deprecated, and I can't find another way to get it. Is there any way to run this program on Fedora 33?

**Comment by kozec** [comment]
Does appimage show same issue? I'm trying to build one for SteamOS currently, which has all dependencies, including python, included. It's apparently feat of engeneering unseen before, but if I manage, it should work on Fedora as well.

**Comment by Scopt97** [comment]
The appimage gave errors related to libffi7 and pixbuf. I downloaded the one you made for this ticket: https://github.com/kozec/sc-controller/issues/622 an it didn't spit out an error, but it also didn't seem to do anything; I still got the invisible mouse cursor from the steam controller, which was my reason for seeking out your app.

Error messages from the main appimage:
```
Traceback (most recent call last):
  File "/tmp/.mount_sc-conou0OmO/usr/bin/scc", line 6, in <module>
    from scc.scripts import main
  File "/tmp/.mount_sc-conou0OmO/usr/lib/python2.7/site-packages/scc/scripts.py", line 8, in <module>
    from scc.tools import init_logging, set_logging_level, find_binary
  File "/tmp/.mount_sc-conou0OmO/usr/lib/python2.7/site-packages/scc/tools.py", line 15, in <module>
    import os, sys, ctypes, imp, shlex, gettext, logging
  File "/tmp/.mount_sc-conou0OmO/usr/lib/python2.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.7: cannot open shared object file: No such file or directory

(zenity:8268): Gtk-WARNING **: 18:30:02.972: Failed to set text 'Traceback (most recent call last):
  File "/tmp/.mount_sc-conou0OmO/usr/bin/scc", line 6, in <module>
    from scc.scripts import main
  File "/tmp/.mount_sc-conou0OmO/usr/lib/python2.7/site-packages/scc/scripts.py", line 8, in <module>
    from scc.tools import init_logging, set_logging_level, find_binary
  File "/tmp/.mount_sc-conou0OmO/usr/lib/python2.7/site-packages/scc/tools.py", line 15, in <module>
    import os, sys, ctypes, imp, shlex, gettext, logging
  File "/tmp/.mount_sc-conou0OmO/usr/lib/python2.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.7: cannot open shared object file: No such file or directory' from markup due to error parsing markup: Error on line 10 char 93: Element “markup” was closed, but the currently open element is “module”

(zenity:8268): Gtk-WARNING **: 18:30:03.000: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
/tmp/.mount_sc-conou0OmO/AppRun: line 28:  8268 Aborted                 (core dumped) "$@"
```
