### ISSUE TITLE
Can't Summon Daemon

### ISSUE THREAD

**Issue by ExploreMyMind** [kozec/sc-controller#677]
Hey everyone, first time ever asking for help with anything on Linux. In terms of my experience with Linux, that's also very "newbish". So you'll have to explain things to me like I'm a little Linux baby. Anyways getting to the issue at hand. 

I'm currently running the latest sc-controller appimage, however, I also followed [this guide](https://www.reddit.com/r/linux_gaming/comments/qgzonh/how_to_setup_dualsense_controller_for_nonsteam/) in hopes of obtaining support for my _Dualsense_ controller.

So that in and of itself could be conflicting with appimage maybe? Getting to the core of the issue, when I run the appimage I get the error "CANT_SUMMON_THE_DAEMON" and when I run "scc-daemon debug" I get this ouput.

scc-daemon debug
D SCCDaemon     Starting SCCDaemon...
D SCCDaemon     Initializing drivers...
Traceback (most recent call last):
  File "/usr/local/bin/scc-daemon", line 36, in <module>
    main()
  File "/usr/local/bin/scc-daemon", line 32, in main
    daemon.debug()
  File "/usr/local/lib/python2.7/dist-packages/scc/sccdaemon.py", line 1097, in debug
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/scc/sccdaemon.py", line 641, in run
    self.init_drivers()
  File "/usr/local/lib/python2.7/dist-packages/scc/sccdaemon.py", line 87, in init_drivers
    mod = getattr(__import__('scc.drivers.%s' % (modname,)).drivers, modname)
  File "/usr/local/lib/python2.7/dist-packages/scc/drivers/ds4drv.py", line 8, in <module>
    from scc.drivers.hiddrv import BUTTON_COUNT, ButtonData, AxisType, AxisData
  File "/usr/local/lib/python2.7/dist-packages/scc/drivers/hiddrv.py", line 14, in <module>
    from scc.drivers.evdevdrv import FIRST_BUTTON, TRIGGERS, parse_axis
  File "/usr/local/lib/python2.7/dist-packages/scc/drivers/evdevdrv.py", line 19, in <module>
    import evdev
  File "/home/wheatie/.local/lib/python2.7/site-packages/evdev/__init__.py", line 7, in <module>
    from evdev.uinput import UInput, UInputError
  File "/home/wheatie/.local/lib/python2.7/site-packages/evdev/uinput.py", line 37
    def from_device(cls, *devices, filtered_types=(ecodes.EV_SYN, ecodes.EV_FF), **kwargs):
                                                ^
SyntaxError: invalid syntax

I'm not sure why evdev would be having a problem (what I'm assuming is loading) loading uinput as it's a built in module on my system and if I run "scc-daemon restart" I get this

pidfile /home/wheatie/.config/scc/daemon.pid does not exist. Daemon not running?

However I ran the command again and didn't get any output so I executed the appimage again and still got the same daemon error. Also having steam open doesn't make any difference in the terminals outputs. All of this was done after a reboot.

If anyone could help I would appreciate it. Let me know if you need me to run any more tests or need any more specific info.

Here's some more issue specific details
Ubuntu 22.04 LTS (Ubuntu Budgie)
64-bit
Python 3.10.4 & Python 2.7.18

**Comment by blueapple128** [comment]
I don't have a DualSense controller, but that error looks particularly bizarre: A SyntaxError like this would usually indicate some sort of Python2 vs. Python3 incompatibility, but there's nothing incompatible next to line 37 of uinput.py and it and the line above don't look like invalid syntax at all.

I've gotten this project working for my use case (Steam Deck), but I didn't touch the appimage and instead built and installed from source.

Ludicrously basic, but does anything change if you `pip2 uninstall evdev` and redo `pip2 install evdev`?
