### ISSUE TITLE
Steam Deck Standby turns off sc-controller

### ISSUE THREAD

**Issue by AsurasWrathX** [kozec/sc-controller#696]
Hey guys,

Overall everything works fine. I mapped all the controls to my liking but after the Steam Deck goes into sleep mode and you turn it back on, sc-controller does not get recognized anymore.

it shows the green light that Emulation is active but the controls are not working anymore.

Stopping and re-enabling emulation fixes the issue but when a game is displayed in fullscreen you are either forced to plug in a keyboard or force power off the Steam Deck.

is there any temporary fix by adding a script when the Steam Deck wakes up or something?

**Comment by wvffle** [comment]
That's what I get when I run `scc daemon debug`. The exception shows up after waking up from sleep.

```
[waff@waffdeck:~]$ scc daemon ~/.config/scc/profiles/Steam\ Deck\ -\ Hyprland.sccprofile debug
D SCCDaemon     Starting SCCDaemon...
D SCCDaemon     Initializing drivers...
W SCCDaemon     Skipping disabled driver 'fake'
W SCCDaemon     Skipping disabled driver 'remotepad'
D USB           Registered USB driver for 054c:09cc
D USB           Registered USB driver for 054c:05c4
D USB           Registered USB driver for 054c:0ce6
D USB           Registered USB driver for 28de:1102
D USB           Registered USB driver for 28de:1142
D USB           Registered USB driver for 28de:1205
D Mapper        Creating virtual devices
D Mapper        Keyboard: <scc.uinput.Keyboard object at 0x7f19ef533290>
D Mapper        Mouse:    <scc.uinput.Mouse object at 0x7f19ef533c90>
D Mapper        Gamepad:  <scc.uinput.UInput object at 0x7f19ef5398d0>
D SCCDaemon     Created control socket /home/waff/.config/scc/daemon.socket
W SCCDaemon     Wayland detected. Disabling X11 support, some functionality will be unavailable
D deck          Got SteamDeck with serial 1:3
D USB           USB device added: 28de:1205
D asyncio       Using selector: EpollSelector
D SCCDaemon     Assigned default_mapper to <Deck deck1:3>
D SCCDaemon     Controller added: <Deck deck1:3>
Exception ignored on calling ctypes callback function: <bound method USBTransfer.__callbackWrapper of <scc.lib.usb1.USBTransfer object at 0x7f19ef57fed0>>
Traceback (most recent call last):
  File "/nix/store/7krqphqyqm4pbrkx1si1pry9q8s1diy2-sc-controller-0.4.8.11/lib/python3.11/site-packages/scc/lib/usb1.py", line 321, in __callbackWrapper
    callback(self)
  File "/nix/store/7krqphqyqm4pbrkx1si1pry9q8s1diy2-sc-controller-0.4.8.11/lib/python3.11/site-packages/scc/drivers/usb.py", line 47, in callback_wrapper
    transfer.submit()
  File "/nix/store/7krqphqyqm4pbrkx1si1pry9q8s1diy2-sc-controller-0.4.8.11/lib/python3.11/site-packages/scc/lib/usb1.py", line 721, in submit
    raiseUSBError(result)
  File "/nix/store/7krqphqyqm4pbrkx1si1pry9q8s1diy2-sc-controller-0.4.8.11/lib/python3.11/site-packages/scc/lib/usb1.py", line 117, in raiseUSBError
    raise STATUS_TO_EXCEPTION_DICT.get(value, USBError)(value)
scc.lib.usb1.USBErrorIO: LIBUSB_ERROR_IO [-1]
```
