### ISSUE TITLE
Doesn't Launch on Ubuntu 22.04

### ISSUE THREAD

**Issue by InklingGirl** [kozec/sc-controller#703]
Neither versions v0.4.8 nor v0.4.8.9 launch on Ubuntu 22.04.

**Comment by Ryochan7** [comment]
Need more details because v0.4.8.9 works on my Ubuntu 22.04 VM. If nothing else, try running the program from source rather than the AppImage

**Comment by InklingGirl** [comment]
I would prefer to run it as an AppImage, & it didn't work on my daily driver bare metal installation or a fresh virtual machine install. What more details would you like @Ryochan7?

**Comment by InklingGirl** [comment]
Yeah, no matter how I try to run them, they just don't run, & I'm just using a fresh install 22.04 in VirtualBox.

**Comment by maxtimbo** [comment]
running the AppImage I get:

```python
Traceback (most recent call last):
  File "/tmp/.mount_sc-conW2IoiD/usr/bin/sc-controller", line 12, in <module>
    gi.require_version('Gtk', '3.0') 
  File "/tmp/.mount_sc-conW2IoiD/usr/lib/python2.7/site-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
```
I'm running X11 on Ubuntu 22.04.2, Gnome 42.5

**Comment by InklingGirl** [comment]
> I'm running X11 on Ubuntu 22.04.2, Gnome 42.5

I'm running Wayland, same OS & DE otherwise, & I get (w/ the AppImage of v0.4.8):
```python
Traceback (most recent call last):
  File "/tmp/.mount_sc-conWm89k8/usr/bin/scc", line 6, in <module>
    from scc.scripts import main
  File "/tmp/.mount_sc-conWm89k8/usr/lib/python2.7/site-packages/scc/scripts.py", line 8, in <module>
    from scc.tools import init_logging, set_logging_level, find_binary
  File "/tmp/.mount_sc-conWm89k8/usr/lib/python2.7/site-packages/scc/tools.py", line 15, in <module>
    import os, sys, ctypes, imp, shlex, gettext, logging
  File "/tmp/.mount_sc-conWm89k8/usr/lib/python2.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.7: cannot open shared object file: No such file or directory

(zenity:10952): GdkPixbuf-WARNING **: 16:42:07.527: Cannot open pixbuf loader module file '/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.

(zenity:10952): Gtk-WARNING **: 16:42:07.585: Failed to set text 'Traceback (most recent call last):
  File "/tmp/.mount_sc-conWm89k8/usr/bin/scc", line 6, in <module>
    from scc.scripts import main
  File "/tmp/.mount_sc-conWm89k8/usr/lib/python2.7/site-packages/scc/scripts.py", line 8, in <module>
    from scc.tools import init_logging, set_logging_level, find_binary
  File "/tmp/.mount_sc-conWm89k8/usr/lib/python2.7/site-packages/scc/tools.py", line 15, in <module>
    import os, sys, ctypes, imp, shlex, gettext, logging
  File "/tmp/.mount_sc-conWm89k8/usr/lib/python2.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.7: cannot open shared object file: No such file or directory' from markup due to error parsing markup: Error on line 10 char 93: Element “markup” was closed, but the currently open element is “module”

(zenity:10952): GdkPixbuf-WARNING **: 16:42:07.639: Cannot open pixbuf loader module file '/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.

(zenity:10952): Gtk-WARNING **: 16:42:07.639: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.

(zenity:10952): GdkPixbuf-WARNING **: 16:42:07.639: Cannot open pixbuf loader module file '/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Yaru/16x16/status/image-missing.png: Unrecognised image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Yaru/16x16/status/image-missing.png: Unrecognised image file format (gdk-pixbuf-error-quark, 3)
/tmp/.mount_sc-conWm89k8/AppRun: line 28: 10952 Aborted                 (core dumped) "$@"
```
(& w/ the AppImage of v0.4.8.9, same as @maxtimbo):
```python
Traceback (most recent call last):
  File "/tmp/.mount_sc-conLhKlKE/usr/bin/sc-controller", line 12, in <module>
    gi.require_version('Gtk', '3.0') 
  File "/tmp/.mount_sc-conLhKlKE/usr/lib/python2.7/site-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
```
Neither version works no matter how I deploy the respective AppImage, in my usual system on bare metal or a freshly installed VM, w/ Wayland or X11, via `AppImageLauncher` or manually. Developer input after months would be appreciated, @Ryochan7.

**Comment by maxtimbo** [comment]
I was going to install from source, but I really don't like the idea of installing outdated, ancient python2x just for this app.

**Comment by InklingGirl** [comment]
@maxtimbo for me, @Ryochan7's [fork](https://github.com/Ryochan7/sc-controller/releases/tag/v0.4.8.9) launches (albeit, it's having issues using my DualShock 4). Try that. If it works, then clearly something is wrong w/ this repository's AppImage or binary therein.

**Comment by Fuseteam** [comment]
i can confirm @Ryochan7's fork launches fine

**Comment by TCMOREIRA** [comment]
> @maxtimbo for me, @Ryochan7's [fork](https://github.com/Ryochan7/sc-controller/releases/tag/v0.4.8.9) launches (albeit, it's having issues using my DualShock 4). Try that. If it works, then clearly something is wrong w/ this repository's AppImage or binary therein.

Can confirm that the fork worked for me as well! Whereas the original wasn't working.
