### ISSUE TITLE
How to install on latest fedora?

### ISSUE THREAD

**Issue by supertriodo** [kozec/sc-controller#722]
I love this project, it's simply amazing and it was working great on my opensuse.

But this summer with a new PC I tried fedora and I can't find a way to install sc-controller.

The installation instruction for fedora (https://software.opensuse.org/download.html?project=home%3Akozec&package=sc-controller) returns a no data webpage.

Thee AppImage of the latest stable version from 2020 output:

> [triodo@fedora Descargas]$ ./sc-controller-0.4.8.glibc-x86_64.appimage 
> Traceback (most recent call last):
>   File "/tmp/.mount_sc-conAfoDFO/usr/bin/scc", line 6, in <module>
>     from scc.scripts import main
>   File "/tmp/.mount_sc-conAfoDFO/usr/lib/python2.7/site-packages/scc/scripts.py", line 8, in <module>
>     from scc.tools import init_logging, set_logging_level, find_binary
>   File "/tmp/.mount_sc-conAfoDFO/usr/lib/python2.7/site-packages/scc/tools.py", line 15, in <module>
>     import os, sys, ctypes, imp, shlex, gettext, logging
>   File "/tmp/.mount_sc-conAfoDFO/usr/lib/python2.7/ctypes/__init__.py", line 7, in <module>
>     from _ctypes import Union, Structure, Array
> ImportError: libffi.so.7: cannot open shared object file: No such file or directory
> 
> (zenity:5236): Gtk-WARNING **: 10:43:40.772: Unknown key gtk-modules in /home/triodo/.config/gtk-4.0/settings.ini
> 
> (zenity:5236): Adwaita-WARNING **: 10:43:40.803: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
> 
> (zenity:5236): Gtk-WARNING **: 10:43:40.826: Failed to set text 'Traceback (most recent call last):
>   File "/tmp/.mount_sc-conAfoDFO/usr/bin/scc", line 6, in <module>
>     from scc.scripts import main
>   File "/tmp/.mount_sc-conAfoDFO/usr/lib/python2.7/site-packages/scc/scripts.py", line 8, in <module>
>     from scc.tools import init_logging, set_logging_level, find_binary
>   File "/tmp/.mount_sc-conAfoDFO/usr/lib/python2.7/site-packages/scc/tools.py", line 15, in <module>
>     import os, sys, ctypes, imp, shlex, gettext, logging
>   File "/tmp/.mount_sc-conAfoDFO/usr/lib/python2.7/ctypes/__init__.py", line 7, in <module>
>     from _ctypes import Union, Structure, Array
> ImportError: libffi.so.7: cannot open shared object file: No such file or directory' from markup due to error parsing markup: Error en la línea 10, carácter 93: Se cerró el elemento «markup», pero el elemento que está abierto actualmente es «module»

The AppImage of the prerelease from 2022 output:

> [triodo@fedora Descargas]$ ./sc-controller-0.4.8+5b42308-x86_64.appimage 
> E root          code for hash md5 was not found.
> Traceback (most recent call last):
>   File "/tmp/.mount_sc-con7JdEb5/usr/lib/python2.7/hashlib.py", line 147, in <module>
>     globals()[__func_name] = __get_hash(__func_name)
>   File "/tmp/.mount_sc-con7JdEb5/usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
>     raise ValueError('unsupported hash type ' + name)
> ValueError: unsupported hash type md5
> E root          code for hash sha1 was not found.
> Traceback (most recent call last):
>   File "/tmp/.mount_sc-con7JdEb5/usr/lib/python2.7/hashlib.py", line 147, in <module>
>     globals()[__func_name] = __get_hash(__func_name)
>   File "/tmp/.mount_sc-con7JdEb5/usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
>     raise ValueError('unsupported hash type ' + name)
> ValueError: unsupported hash type sha1
> E root          code for hash sha224 was not found.
> Traceback (most recent call last):
>   File "/tmp/.mount_sc-con7JdEb5/usr/lib/python2.7/hashlib.py", line 147, in <module>
>     globals()[__func_name] = __get_hash(__func_name)
>   File "/tmp/.mount_sc-con7JdEb5/usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
>     raise ValueError('unsupported hash type ' + name)
> ValueError: unsupported hash type sha224
> E root          code for hash sha256 was not found.
> Traceback (most recent call last):
>   File "/tmp/.mount_sc-con7JdEb5/usr/lib/python2.7/hashlib.py", line 147, in <module>
>     globals()[__func_name] = __get_hash(__func_name)
>   File "/tmp/.mount_sc-con7JdEb5/usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
>     raise ValueError('unsupported hash type ' + name)
> ValueError: unsupported hash type sha256
> E root          code for hash sha384 was not found.
> Traceback (most recent call last):
>   File "/tmp/.mount_sc-con7JdEb5/usr/lib/python2.7/hashlib.py", line 147, in <module>
>     globals()[__func_name] = __get_hash(__func_name)
>   File "/tmp/.mount_sc-con7JdEb5/usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
>     raise ValueError('unsupported hash type ' + name)
> ValueError: unsupported hash type sha384
> E root          code for hash sha512 was not found.
> Traceback (most recent call last):
>   File "/tmp/.mount_sc-con7JdEb5/usr/lib/python2.7/hashlib.py", line 147, in <module>
>     globals()[__func_name] = __get_hash(__func_name)
>   File "/tmp/.mount_sc-con7JdEb5/usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
>     raise ValueError('unsupported hash type ' + name)
> ValueError: unsupported hash type sha512
> free(): invalid pointer

Any idea? and thanks for such an amazing work you have done with this esential linux app!

**Comment by kozec** [comment]
Yeah, sorry about OBS, it kinda kicked me out some time ago.

I'll try to rebuild appimage using updated libs, maybe it will work on more recent distros that way.

**Comment by supertriodo** [comment]
That would be great, thanks so much!

**Comment by kozec** [comment]
Just as a test, will this "build" work for you?

https://files.catbox.moe/h8czql.gz

**Comment by supertriodo** [comment]
No luck.

> [triodo@fedora Apps]$ ./SC_Controller-x86_64.AppImage 
> E root          code for hash md5 was not found.
> Traceback (most recent call last):
>   File "/tmp/.mount_SC_ConXeta8T/usr/lib/python2.7/hashlib.py", line 147, in <module>
>     globals()[__func_name] = __get_hash(__func_name)
>   File "/tmp/.mount_SC_ConXeta8T/usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
>     raise ValueError('unsupported hash type ' + name)
> ValueError: unsupported hash type md5
> E root          code for hash sha1 was not found.
> Traceback (most recent call last):
>   File "/tmp/.mount_SC_ConXeta8T/usr/lib/python2.7/hashlib.py", line 147, in <module>
>     globals()[__func_name] = __get_hash(__func_name)
>   File "/tmp/.mount_SC_ConXeta8T/usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
>     raise ValueError('unsupported hash type ' + name)
> ValueError: unsupported hash type sha1
> E root          code for hash sha224 was not found.
> Traceback (most recent call last):
>   File "/tmp/.mount_SC_ConXeta8T/usr/lib/python2.7/hashlib.py", line 147, in <module>
>     globals()[__func_name] = __get_hash(__func_name)
>   File "/tmp/.mount_SC_ConXeta8T/usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
>     raise ValueError('unsupported hash type ' + name)
> ValueError: unsupported hash type sha224
> E root          code for hash sha256 was not found.
> Traceback (most recent call last):
>   File "/tmp/.mount_SC_ConXeta8T/usr/lib/python2.7/hashlib.py", line 147, in <module>
>     globals()[__func_name] = __get_hash(__func_name)
>   File "/tmp/.mount_SC_ConXeta8T/usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
>     raise ValueError('unsupported hash type ' + name)
> ValueError: unsupported hash type sha256
> E root          code for hash sha384 was not found.
> Traceback (most recent call last):
>   File "/tmp/.mount_SC_ConXeta8T/usr/lib/python2.7/hashlib.py", line 147, in <module>
>     globals()[__func_name] = __get_hash(__func_name)
>   File "/tmp/.mount_SC_ConXeta8T/usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
>     raise ValueError('unsupported hash type ' + name)
> ValueError: unsupported hash type sha384
> E root          code for hash sha512 was not found.
> Traceback (most recent call last):
>   File "/tmp/.mount_SC_ConXeta8T/usr/lib/python2.7/hashlib.py", line 147, in <module>
>     globals()[__func_name] = __get_hash(__func_name)
>   File "/tmp/.mount_SC_ConXeta8T/usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
>     raise ValueError('unsupported hash type ' + name)
> ValueError: unsupported hash type sha512
> free(): invalid pointer
> [triodo@fedora Apps]$

**Comment by kozec** [comment]
Ok, I have vague idea where this comes from, but I have yet to find how whether only solution is to build one's own openssl. If you have some kind of compact package available in fedora, installing it may work as temporar workaround.

**Comment by supertriodo** [comment]
I'm sorry but I'm new to fedora, don't really know how to look for a compact openssl package.

**Comment by jeremiel26** [comment]
Hi, tried to lauch appimage on fedora 38, got "An error as occured" window and this terminal output:

$ LANG=C ./sc-controller-0.4.8.glibc-x86_64.AppImage 
Traceback (most recent call last):
  File "/tmp/.mount_sc-conW01EpD/usr/bin/scc", line 6, in <module>
    from scc.scripts import main
  File "/tmp/.mount_sc-conW01EpD/usr/lib/python2.7/site-packages/scc/scripts.py", line 8, in <module>
    from scc.tools import init_logging, set_logging_level, find_binary
  File "/tmp/.mount_sc-conW01EpD/usr/lib/python2.7/site-packages/scc/tools.py", line 15, in <module>
    import os, sys, ctypes, imp, shlex, gettext, logging
  File "/tmp/.mount_sc-conW01EpD/usr/lib/python2.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.7: cannot open shared object file: No such file or directory

(zenity:101382): Gtk-WARNING **: 17:36:30.294: Theme parser error: gtk.css:4052:3-22: No property named "-gtk-outline-radius"

(zenity:101382): Gtk-WARNING **: 17:36:30.294: Theme parser error: gtk.css:4169:3-29: No property named "-GtkWidget-window-dragging"

(zenity:101382): Gtk-WARNING **: 17:36:30.295: Theme parser error: gtk.css:4183:9-37: No property named "-gtk-outline-top-left-radius"

(zenity:101382): Gtk-WARNING **: 17:36:30.295: Theme parser error: gtk.css:4185:9-38: No property named "-gtk-outline-top-right-radius"

(zenity:101382): Gtk-WARNING **: 17:36:30.295: Theme parser error: gtk.css:4188:9-40: No property named "-gtk-outline-bottom-left-radius"

(zenity:101382): Gtk-WARNING **: 17:36:30.295: Theme parser error: gtk.css:4190:9-41: No property named "-gtk-outline-bottom-right-radius"

(zenity:101382): Gtk-WARNING **: 17:36:30.295: Theme parser error: gtk.css:4193:5-33: No property named "-gtk-outline-top-left-radius"

(zenity:101382): Gtk-WARNING **: 17:36:30.295: Theme parser error: gtk.css:4195:5-34: No property named "-gtk-outline-top-right-radius"

(zenity:101382): Gtk-WARNING **: 17:36:30.295: Theme parser error: gtk.css:4198:5-36: No property named "-gtk-outline-bottom-left-radius"

(zenity:101382): Gtk-WARNING **: 17:36:30.295: Theme parser error: gtk.css:4200:5-37: No property named "-gtk-outline-bottom-right-radius"

(zenity:101382): Gtk-WARNING **: 17:36:30.295: Theme parser error: gtk.css:4206:7-36: No property named "-gtk-outline-top-right-radius"

(zenity:101382): Gtk-WARNING **: 17:36:30.295: Theme parser error: gtk.css:4208:7-39: No property named "-gtk-outline-bottom-right-radius"

(zenity:101382): Gtk-WARNING **: 17:36:30.295: Theme parser error: gtk.css:4211:7-35: No property named "-gtk-outline-top-left-radius"

(zenity:101382): Gtk-WARNING **: 17:36:30.295: Theme parser error: gtk.css:4213:7-38: No property named "-gtk-outline-bottom-left-radius"

(zenity:101382): Gtk-WARNING **: 17:36:30.295: Theme parser error: gtk.css:4287:23-37: Not a valid image

(zenity:101382): Gtk-WARNING **: 17:36:30.295: Theme parser error: gtk.css:4326:3-31: No property named "-gtk-outline-top-left-radius"

(zenity:101382): Gtk-WARNING **: 17:36:30.295: Theme parser error: gtk.css:4328:3-32: No property named "-gtk-outline-top-right-radius"

(zenity:101382): Gtk-WARNING **: 17:36:30.295: Theme parser error: gtk.css:4335:3-34: No property named "-gtk-outline-bottom-left-radius"

(zenity:101382): Gtk-WARNING **: 17:36:30.296: Theme parser error: gtk.css:4337:3-35: No property named "-gtk-outline-bottom-right-radius"

(zenity:101382): Gtk-WARNING **: 17:36:30.297: Theme parser error: gtk.css:5017:12-17: "shade" is not a valid color name.

(zenity:101382): Gtk-WARNING **: 17:36:30.297: Theme parser error: gtk.css:5077:12-17: "shade" is not a valid color name.

(zenity:101382): Gtk-WARNING **: 17:36:30.297: Theme parser error: gtk.css:5104:12-15: "mix" is not a valid color name.

(zenity:101382): Gtk-WARNING **: 17:36:30.297: Theme parser error: gtk.css:5108:12-15: "mix" is not a valid color name.

(zenity:101382): Gtk-WARNING **: 17:36:30.297: Theme parser warning: gtk.css:5309:3-5310:1: Expected ';' at end of block

(zenity:101382): Gtk-WARNING **: 17:36:30.297: Theme parser error: gtk.css:5340:3-19: No property named "-gtk-icon-effect"

(zenity:101382): Gtk-WARNING **: 17:36:30.409: Failed to set text 'Traceback (most recent call last):
  File "/tmp/.mount_sc-conW01EpD/usr/bin/scc", line 6, in <module>
    from scc.scripts import main
  File "/tmp/.mount_sc-conW01EpD/usr/lib/python2.7/site-packages/scc/scripts.py", line 8, in <module>
    from scc.tools import init_logging, set_logging_level, find_binary
  File "/tmp/.mount_sc-conW01EpD/usr/lib/python2.7/site-packages/scc/tools.py", line 15, in <module>
    import os, sys, ctypes, imp, shlex, gettext, logging
  File "/tmp/.mount_sc-conW01EpD/usr/lib/python2.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.7: cannot open shared object file: No such file or directory' from markup due to error parsing markup: Error on line 10 char 93: Element ?markup? was closed, but the currently open element is ?module?

**Comment by PoorPocketsMcNewHold** [comment]
> Ok, I have vague idea where this comes from, but I have yet to find how whether only solution is to build one's own openssl. If you have some kind of compact package available in fedora, installing it may work as temporar workaround.

Probably meant, `compat` no?
We do have `openssl.1.1` on Fedora, but it just makes a 
`free(): invalid pointer` error.

**Comment by alterNERDtive** [comment]
It appears both the build service builds and the AppImage are still broken. So before I start building and/or fixing things myself, is there a point? Or is more of this unmaintained?

Don’t get me wrong, that would be fine. Nobody is entitled to free software being maintained indefinitely. But I wouldn’t invest my time on top in that case :)
