### ISSUE TITLE
Error when opening the import dialog

### ISSUE THREAD

**Issue by edward81** [kozec/sc-controller#85]
> E ImportDialog  unsupported operand type(s) for +: 'NoneType' and 'int'
Traceback (most recent call last):  
  File "/usr/lib/python2.7/site-packages/scc/gui/import_dialog.py", line 59, in _load_profiles  
    i = self._parse_profile_list(i, sharedconfig)  
  File "/usr/lib/python2.7/site-packages/scc/gui/import_dialog.py", line 88, in _parse_profile_list
    i = i+ 1
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
E ImportDialog  unsupported operand type(s) for +: 'NoneType' and 'int'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/scc/gui/import_dialog.py", line 59, in _load_profiles
    i = self._parse_profile_list(i, sharedconfig)
  File "/usr/lib/python2.7/site-packages/scc/gui/import_dialog.py", line 88, in _parse_profile_list
    i = i+ 1
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

Var "i" around line 88 on import_dialog.py is not initialized.

**Comment by kozec** [comment]
It is, it's argument of that method. Something else has to be broken here...

**Comment by kozec** [comment]
I really have trouble finding how that can be None.

What version of SCC are you using? Is there anything special (like non-default location of .steam directory, having no profiles, multiple steam user accounts...) on your system?
