### ISSUE TITLE
OSD fails without an active window.

### ISSUE THREAD

**Issue by richese** [kozec/sc-controller#99]
Hi,
OSD daemon fails when I try to open any OSD menu while there are no open windows in current workspace ('desktop'?).
I am using [i3](http://i3wm.org) as window manager but I don't have any desktop environments on my PC so I can't tell if it's a WM specific thing or not.

Traceback from `> scc-daemon debug`:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/scc/x11/scc-osd-daemon.py", line 164, in on_unknown_message
    self._window.show()
  File "/usr/lib/python2.7/site-packages/scc/osd/menu.py", line 279, in show
    OSDWindow.show(self, *a)
  File "/usr/lib/python2.7/site-packages/scc/osd/__init__.py", line 187, in show
    geometry = screen.get_monitor_geometry(screen.get_monitor_at_window(screen.get_active_window()))
TypeError: Argument 1 does not allow None as a value
```
Any atempt to open menu after this error results in:
```
W OSD osd.daemon    Another OSD is already visible - refusing to show menu
```

**Comment by kozec** [comment]
It may be i3 related, as normally there should be always some active window - if nothing else, then root window.
